"""
gen_stubs.py - Emit stub definitions for unresolved cross-segment call targets.

A few call targets still land where no function was recovered, so the symbol the
lifted code calls has no definition. This writes one, so the program links.

The stub cannot do the callee's work, but it MUST do the callee's stack cleanup.
The lifted call sites push the return frame themselves -- 4 bytes for a far call
(`push cs; push 0`) and 2 for a near one -- and the real function would pop it
on RET/RETF. A stub that just returns leaks that frame, and the caller's own
`pop`s then read the wrong words: one no-op stub in the video driver's init cost
4 bytes and left DS pointing at the wrong segment, which turned the next vtable
read into a null far call. Silent, and a long way from the cause.

So each stub is emitted with the frame size its call sites actually push, read
back out of the generated source. A stub is still a coverage gap -- it does
nothing and returns nothing -- but at least it returns cleanly.
"""
import os
import re
import glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(SRC, '_unresolved_stubs.c')

DEF_RE = re.compile(r'^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)', re.M)
CALL_RE = re.compile(r'\b(seg\d+_[0-9A-Fa-f]+)\(cpu\)')
PUSH_CS_RE = re.compile(r'push16\(cpu, (?:cpu->cs|SEG_\d+)\)')
PUSH_RET_RE = re.compile(r'push16\(cpu, 0(?:xFFFF)?\)')


def main():
    defined = set()
    called = set()
    for path in glob.glob(os.path.join(SRC, '*.c')):
        if os.path.basename(path) == os.path.basename(OUT):
            continue
        text = open(path, encoding='utf-8', errors='replace').read()
        defined.update(DEF_RE.findall(text))
        called.update(CALL_RE.findall(text))

    undefined = sorted(called - defined)

    # Work out each stub's frame size from how its call sites push. The lifter
    # emits a far frame as two pushes (`push cs` then the return placeholder) and
    # a near one as a single `push16(cpu, 0)` / `push16(cpu, 0xFFFF)`.
    frame = {}
    for path in glob.glob(os.path.join(SRC, '*.c')):
        # _dispatch.c reaches a stub through dispatch_far/dispatch_near, where the
        # frame was pushed by whoever called the dispatcher, so its call sites say
        # nothing about the size. Judge only from the direct call sites.
        if os.path.basename(path) in (os.path.basename(OUT), '_dispatch.c'):
            continue
        lines = open(path, encoding='utf-8', errors='replace').read().splitlines()
        for i, line in enumerate(lines):
            m = CALL_RE.search(line)
            if not m or m.group(1) not in undefined:
                continue
            prev = ' '.join(lines[max(0, i - 2):i])
            # A tail call (from a lifted jmp) pushes nothing, but the callee still
            # pops the frame the original caller pushed -- so take the largest any
            # site implies rather than the smallest.
            n = 4 if PUSH_CS_RE.search(prev) else (2 if PUSH_RET_RE.search(prev) else 0)
            frame[m.group(1)] = max(frame.get(m.group(1), 0), n)

    lines = [
        '/* _unresolved_stubs.c - Auto-generated by gen_stubs.py */',
        '/* NO-OP stubs for call targets the disassembler could not align to an */',
        '/* instruction boundary (data-in-code desync). Coverage gap, not final. */',
        '',
        '#include "segments.h"',
        '',
    ]
    for name in undefined:
        # Reached only through the dispatcher, or only by tail call: assume a far
        # frame, which is what a cross-segment target almost always is.
        n = frame.get(name) or 4
        body = f'cpu->sp += {n};' if n else '(void)cpu;'
        lines.append(f'void {name}(CPU *cpu) {{ {body} /* UNRESOLVED target */ }}')
    lines.append('')

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {OUT}: {len(undefined)} unresolved stubs '
          f'({len(defined)} real functions, {len(called)} distinct call targets)')


if __name__ == '__main__':
    main()
