/* Segment 131 - 241 bytes, 4 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "cpu.h"
#include "fpu.h"
#include <math.h>

void seg131_0000(CPU *cpu);
void seg131_0032(CPU *cpu);
void seg131_0068(CPU *cpu);
void seg131_00BA(CPU *cpu);

void seg131_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->es);                    /* push es */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->di);                    /* push di */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, cpu->ax)); /* add di, ax */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8)); /* lds si, word ss:[bp+0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x8) + 2));
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
L_seg131_0000_000015:;
L_seg131_0000_000015:;
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280)), cpu->al); /* cmp byte es:[di+0x280], al */
    if (cc_ae(cpu)) goto L_seg131_0000_000026; /* jae 0x0026 */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280), (uint8_t)(cpu->al)); /* mov byte es:[di+0x280], al */
    mem_write8(cpu, cpu->es, cpu->di, mem_read8(cpu, cpu->ds, cpu->si)); cpu->si += df(cpu) ? -1 : 1; cpu->di += df(cpu) ? -1 : 1; /* movsb */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_0000_000015; /* loop 0x0015 */
    goto L_seg131_0000_00002A;               /* jmp 0x002A */
L_seg131_0000_000026:;
L_seg131_0000_000026:;
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_0000_000015; /* loop 0x0015 */
L_seg131_0000_00002A:;
L_seg131_0000_00002A:;
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->es = (uint16_t)(pop16(cpu));        /* pop es */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->bp = (uint16_t)(pop16(cpu));        /* pop bp */
    cpu->sp += 0xA; return;                  /* retf 0x6 */
}

void seg131_0032(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->es);                    /* push es */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->di);                    /* push di */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, cpu->ax)); /* add di, ax */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8)); /* lds si, word ss:[bp+0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x8) + 2));
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, cpu->dx)); /* add si, dx */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
L_seg131_0032_000049:;
L_seg131_0032_000049:;
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280)), cpu->al); /* cmp byte es:[di+0x280], al */
    if (cc_ae(cpu)) goto L_seg131_0032_00005C; /* jae 0x005C */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280), (uint8_t)(cpu->al)); /* mov byte es:[di+0x280], al */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_sub16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec si */
    mem_write8(cpu, cpu->es, cpu->di, mem_read8(cpu, cpu->ds, cpu->si)); cpu->si += df(cpu) ? -1 : 1; cpu->di += df(cpu) ? -1 : 1; /* movsb */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_sub16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec si */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_0032_000049; /* loop 0x0049 */
    goto L_seg131_0032_000060;               /* jmp 0x0060 */
L_seg131_0032_00005C:;
L_seg131_0032_00005C:;
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_sub16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec si */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_0032_000049; /* loop 0x0049 */
L_seg131_0032_000060:;
L_seg131_0032_000060:;
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->es = (uint16_t)(pop16(cpu));        /* pop es */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->bp = (uint16_t)(pop16(cpu));        /* pop bp */
    cpu->sp += 0xA; return;                  /* retf 0x6 */
}

void seg131_0068(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    push16(cpu, cpu->es);                    /* push es */
    push16(cpu, cpu->di);                    /* push di */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, cpu->ax)); /* add di, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov al, byte ss:[bp+0x6] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280)), cpu->al); /* cmp byte es:[di+0x280], al */
    if (cc_ae(cpu)) goto L_seg131_0068_000085; /* jae 0x0085 */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280), (uint8_t)(cpu->al)); /* mov byte es:[di+0x280], al */
    mem_write8(cpu, cpu->es, cpu->di, (uint8_t)(cpu->dl)); /* mov byte es:[di], dl */
L_seg131_0068_000085:;
L_seg131_0068_000085:;
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->es = (uint16_t)(pop16(cpu));        /* pop es */
    cpu->bp = (uint16_t)(pop16(cpu));        /* pop bp */
    cpu->sp += 0x6; return;                  /* retf 0x2 */
}

void seg131_00BA(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->es);                    /* push es */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, cpu->cx)); /* add si, cx */
    cpu->di = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); /* les di, word ss:[bp+0x6] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x6) + 2));
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, cpu->ax)); /* add di, ax */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->ax)); /* sub bx, ax */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
L_seg131_00BA_0000D0:;
L_seg131_00BA_0000D0:;
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x280))); /* mov al, byte ds:[si+0x280] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280)), cpu->al); /* cmp byte es:[di+0x280], al */
    if (cc_ae(cpu)) goto L_seg131_00BA_0000E5; /* jae 0x00E5 */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x280), (uint8_t)(cpu->al)); /* mov byte es:[di+0x280], al */
    mem_write8(cpu, cpu->es, cpu->di, mem_read8(cpu, cpu->ds, cpu->si)); cpu->si += df(cpu) ? -1 : 1; cpu->di += df(cpu) ? -1 : 1; /* movsb */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_00BA_0000D0; /* loop 0x00D0 */
    goto L_seg131_00BA_0000E9;               /* jmp 0x00E9 */
L_seg131_00BA_0000E5:;
L_seg131_00BA_0000E5:;
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    cpu->cx--; if (cpu->cx != 0) goto L_seg131_00BA_0000D0; /* loop 0x00D0 */
L_seg131_00BA_0000E9:;
L_seg131_00BA_0000E9:;
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->es = (uint16_t)(pop16(cpu));        /* pop es */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->bp = (uint16_t)(pop16(cpu));        /* pop bp */
    cpu->sp += 0x8; return;                  /* retf 0x4 */
}

