/* Segment 179 - 2367 bytes, 4 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "cpu.h"
#include "fpu.h"
#include <math.h>

void seg179_0030(CPU *cpu);
void seg179_0284(CPU *cpu);
void seg179_045E(CPU *cpu);
void seg179_0658(CPU *cpu);

void seg179_0030(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x6)); /* sub sp, 0x6 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x2], bx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0xA6);              /* mov ax, 0xA6 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_0000(cpu);                        /* call 0000:06CE */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x6], bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    cpu->dx = (uint16_t)(SEG_72);            /* mov dx, 0x2E0  /* selector for seg72 */ */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x20F)); /* push word ds:[0x20F] */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->dx = (uint16_t)(0x13);              /* mov dx, 0x13 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x4)); /* lea ax, word ds:[bx+0x4] */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg208_11DA(cpu);                        /* call 0000:001C */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)); /* les bx, word ss:[bp+-0x6] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x6) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x4)); /* lea ax, word ds:[bx+0x4] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg139_006C(cpu);                        /* call 0000:02E9 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)); /* les bx, word ss:[bp+-0x6] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x6) + 2));
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x5A), (uint16_t)(cpu->ax)); /* mov word es:[bx+0x5A], ax */
    flags_cmp16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x5A)), 0xFFFF); /* cmp word es:[bx+0x5A], 0xFFFF */
    if (cc_ne(cpu)) goto L_seg179_0030_000094; /* jne 0x0094 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x6)); /* lea ax, word ss:[bp+-0x6] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_00C0(cpu);                        /* call 0000:0114 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg179_0030_0000D6;               /* jmp 0x00D6 */
L_seg179_0030_000094:;
L_seg179_0030_000094:;
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ds, 0x20F, (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, 0x20F), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ds:[0x20F] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x5A))); /* mov ax, word es:[bx+0x5A] */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg200_0D89(cpu);                        /* call 0000:0153 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)); /* lds bx, word ss:[bp+-0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x6) + 2));
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    mem_write16(cpu, cpu->ds, cpu->bx, (uint16_t)(cpu->ax)); /* mov word ds:[bx], ax */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x58)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x58), (uint16_t)(_r)); } /* and word ds:[bx+0x58], 0x0 */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
    goto L_seg179_0030_0000C8;               /* jmp 0x00C8 */
L_seg179_0030_0000B4:;
L_seg179_0030_0000B4:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x5A))); /* mov ax, word ds:[bx+0x5A] */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bx + 0x66)); /* lea bx, word ds:[bx+0x66] */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->dx = (uint16_t)(0x40);              /* mov dx, 0x40 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg209_0A89(cpu);                        /* call 0000:01C1 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)); /* lds ax, word ss:[bp+-0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x6) + 2));
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
L_seg179_0030_0000C8:;
L_seg179_0030_0000C8:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)); /* lds bx, word ss:[bp+-0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x6) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ax, word ss:[bp+-0x2] */
    flags_cmp16(cpu, cpu->si, cpu->ax);      /* cmp si, ax */
    if (cc_l(cpu)) goto L_seg179_0030_0000B4; /* jl 0x00B4 */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
L_seg179_0030_0000D6:;
L_seg179_0030_0000D6:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg179_0284(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4C)); /* sub sp, 0x4C */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x2], cx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x6], di */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x4], ds */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->di; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, di */
    if (cc_ne(cpu)) goto L_seg179_0284_0002A5; /* jne 0x02A5 */
L_seg179_0284_0002A1:;
L_seg179_0284_0002A1:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg179_0284_0002F7;               /* jmp 0x02F7 */
L_seg179_0284_0002A5:;
L_seg179_0284_0002A5:;
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x5A)), 0xFFFF); /* cmp word ds:[di+0x5A], 0xFFFF */
    if (cc_e(cpu)) goto L_seg179_0284_0002A1; /* je 0x02A1 */
    flags_logic16(cpu, cpu->cx & cpu->cx);   /* test cx, cx */
    if (cc_ne(cpu)) goto L_seg179_0284_0002B3; /* jne 0x02B3 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg179_0284_0002F7;               /* jmp 0x02F7 */
L_seg179_0284_0002B3:;
L_seg179_0284_0002B3:;
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x58)), 0x0); /* cmp word ds:[di+0x58], 0x0 */
    if (cc_ne(cpu)) goto L_seg179_0284_0002BD; /* jne 0x02BD */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg179_0284_0002F7;               /* jmp 0x02F7 */
L_seg179_0284_0002BD:;
L_seg179_0284_0002BD:;
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg179_0000(cpu);                        /* call 0x0000 */
    cpu->si = (uint16_t)(0x40);              /* mov si, 0x40 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x5A))); /* mov ax, word ds:[di+0x5A] */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea bx, word ss:[bp+-0x46] */
    cpu->cx = (uint16_t)(cpu->ss);           /* mov cx, ss */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    /* unresolved far call call 0000:0920 */ /* call 0000:0920 */
    flags_cmp16(cpu, cpu->ax, cpu->si);      /* cmp ax, si */
    if (cc_e(cpu)) goto L_seg179_0284_0002DF; /* je 0x02DF */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg179_0284_0002F7;               /* jmp 0x02F7 */
L_seg179_0284_0002DF:;
L_seg179_0284_0002DF:;
    cpu->bx = (uint16_t)(0x402);             /* mov bx, 0x402 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x48), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x48], bx */
    cpu->ax = (uint16_t)(0x7);               /* mov ax, 0x7 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4A], ax */
    flags_cmp16(cpu, cpu->ax, 0xFFFF);       /* cmp ax, 0xFFFF */
    if (cc_ne(cpu)) goto L_seg179_0284_0002FA; /* jne 0x02FA */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg179_0284_0002F7:;
L_seg179_0284_0002F7:;
    goto L_seg179_0284_0003AD;               /* jmp 0x03AD */
L_seg179_0284_0002FA:;
L_seg179_0284_0002FA:;
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C), (uint16_t)(_r)); } /* and word ss:[bp+-0x4C], 0x0 */
    goto L_seg179_0284_00031C;               /* jmp 0x031C */
L_seg179_0284_00030A:;
L_seg179_0284_00030A:;
    cpu->bx = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea bx, word ss:[bp+-0x46] */
    cpu->cx = (uint16_t)(cpu->ss);           /* mov cx, ss */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A))); /* mov ax, word ss:[bp+-0x4A] */
    /* unresolved far call call 0000:0453 */ /* call 0000:0453 */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ss:[bp+-0x4C] */
L_seg179_0284_00031C:;
L_seg179_0284_00031C:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x5A))); /* mov ax, word ds:[di+0x5A] */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea bx, word ss:[bp+-0x46] */
    cpu->cx = (uint16_t)(cpu->ss);           /* mov cx, ss */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    /* unresolved far call call 0000:02D3 */ /* call 0000:02D3 */
    flags_cmp16(cpu, cpu->ax, cpu->si);      /* cmp ax, si */
    if (cc_e(cpu)) goto L_seg179_0284_00030A; /* je 0x030A */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov cx, word ss:[bp+-0x2] */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov ds, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg179_0000(cpu);                        /* call 0x0000 */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A))); /* mov ax, word ss:[bp+-0x4A] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
L_seg179_0284_00034D:;
L_seg179_0284_00034D:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C))); /* mov ax, word ss:[bp+-0x4C] */
    flags_cmp16(cpu, cpu->di, cpu->ax);      /* cmp di, ax */
    if (cc_ge(cpu)) goto L_seg179_0284_00037C; /* jge 0x037C */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea bx, word ss:[bp+-0x46] */
    cpu->cx = (uint16_t)(cpu->ss);           /* mov cx, ss */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A))); /* mov ax, word ss:[bp+-0x4A] */
    /* unresolved far call call 0000:0327 */ /* call 0000:0327 */
    flags_cmp16(cpu, cpu->ax, cpu->si);      /* cmp ax, si */
    if (cc_ne(cpu)) goto L_seg179_0284_00037C; /* jne 0x037C */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x5A))); /* mov ax, word ds:[bx+0x5A] */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea bx, word ss:[bp+-0x46] */
    cpu->cx = (uint16_t)(cpu->ss);           /* mov cx, ss */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    /* unresolved far call call 0000:0315 */ /* call 0000:0315 */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    goto L_seg179_0284_00034D;               /* jmp 0x034D */
L_seg179_0284_00037C:;
L_seg179_0284_00037C:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A))); /* mov ax, word ss:[bp+-0x4A] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x7);               /* mov ax, 0x7 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x48))); /* mov bx, word ss:[bp+-0x48] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov si, word ss:[bp+-0x6] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5A))); /* mov ax, word ds:[si+0x5A] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg209_0D81(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5A))); /* mov ax, word ds:[si+0x5A] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg200_0D89(cpu);                        /* call 0000:02FF */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x58), (uint16_t)(flags_sub16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x58)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec word ds:[si+0x58] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x58))); /* mov ax, word ds:[si+0x58] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
L_seg179_0284_0003AD:;
L_seg179_0284_0003AD:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg179_045E(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4A)); /* sub sp, 0x4A */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x2], bx */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg139_0060(cpu);                        /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg179_045E_00048E; /* jne 0x048E */
    cpu->ax = (uint16_t)(0x552);             /* mov ax, 0x552 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(0x2D);              /* mov ax, 0x2D */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x280);                      /* push 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_08AA(cpu);                        /* call 0000:001C */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg179_045E_0004EE;               /* jmp 0x04EE */
L_seg179_045E_00048E:;
L_seg179_045E_00048E:;
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)) | 0xFFFF; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(_r)); } /* or word ss:[bp+-0x6], 0xFFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4A)); /* lea ax, word ss:[bp+-0x4A] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:053F */ /* call 0000:053F */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x66)); /* lea ax, word ds:[si+0x66] */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ds, word ss:[bp+-0x2] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->dx = (uint16_t)(0x40);              /* mov dx, 0x40 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg153_02D6(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x66)); /* lea ax, word ds:[si+0x66] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x4A)); /* lea cx, word ss:[bp+-0x4A] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg153_0000(cpu);                        /* call 0000:0498 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x66)); /* lea ax, word ds:[si+0x66] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5C), (uint16_t)(cpu->ax)); /* mov word ds:[si+0x5C], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5E), (uint16_t)(cpu->dx)); /* mov word ds:[si+0x5E], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5E))); /* mov ax, word ds:[si+0x5E] */
    { uint16_t _r = cpu->ax | mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5C)); flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, word ds:[si+0x5C] */
    if (cc_ne(cpu)) goto L_seg179_045E_0004F0; /* jne 0x04F0 */
    cpu->bx = (uint16_t)(0x479);             /* mov bx, 0x479 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x66)); /* lea ax, word ds:[si+0x66] */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->ax = (uint16_t)(0x41);              /* mov ax, 0x41 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x280);                      /* push 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_08AA(cpu);                        /* call 0000:001C */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg179_045E_0004EE:;
L_seg179_045E_0004EE:;
    goto L_seg179_045E_000517;               /* jmp 0x0517 */
L_seg179_045E_0004F0:;
L_seg179_045E_0004F0:;
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x5C)); /* les bx, word ds:[si+0x5C] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x5C) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x2C3))); /* mov ax, word es:[bx+0x2C3] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x2C5))); /* mov bx, word es:[bx+0x2C5] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->si + 0xA0), (uint8_t)(cpu->al)); /* mov byte ds:[si+0xA0], al */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg179_01CC(cpu);                        /* call 0x01CC */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x5C)); /* lea ax, word ds:[si+0x5C] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
L_seg179_045E_000517:;
L_seg179_045E_000517:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg179_0658(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8C)); /* sub sp, 0x8C */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->bx = (uint16_t)(0x12C);             /* mov bx, 0x12C */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg179_0030(cpu);                        /* call 0x0030 */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x2], ax */
    cpu->dx = (uint16_t)(cpu->ax);           /* mov dx, ax */
    { uint16_t _r = cpu->dx | cpu->si; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* or dx, si */
    if (cc_ne(cpu)) goto L_seg179_0658_000684; /* jne 0x0684 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg179_0658_000892;               /* jmp 0x0892 */
L_seg179_0658_000684:;
L_seg179_0658_000684:;
    cpu->di = (uint16_t)(0x8B3);             /* mov di, 0x8B3 */
    cpu->bx = (uint16_t)(cpu->cx);           /* mov bx, cx */
    flags_cmp16(cpu, cpu->bx, 0x8);          /* cmp bx, 0x8 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si - 0x2EFF)), 0xFFE3); /* cmp word ss:[bp+si+-0x2EFF], 0xFFE3 */
    /* indirect jmp via mem_read16(cpu, cpu->cs, (uint16_t)(cpu->bx + 0x898)) - needs dispatch */ /* jmp word cs:[bx+0x898] */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x102);             /* mov bx, 0x102 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0xF9);              /* mov cx, 0xF9 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x105);             /* mov ax, 0x105 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x10E);             /* mov ax, 0x10E */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x103);             /* mov cx, 0x103 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg179_0658_0006C8:;
L_seg179_0658_0006C8:;
    { uint8_t _r = cpu->bl ^ cpu->bl; flags_logic8(cpu, _r); cpu->bl = (uint8_t)(_r); } /* xor bl, bl */
    cpu->ax = (uint16_t)(0x1194);            /* mov ax, 0x1194 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4C], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4A), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x4A], dx */
    { uint16_t _r = cpu->dx | cpu->ax; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* or dx, ax */
    if (cc_ne(cpu)) goto L_seg179_0658_0006F6; /* jne 0x06F6 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg179_00DC(cpu);                        /* call 0x00DC */
    push16(cpu, 0xFFFF);                     /* push 0xFFFF */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    cpu->cx = (uint16_t)(0x1FA);             /* mov cx, 0x1FA */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg179_0658_0006F6:;
L_seg179_0658_0006F6:;
    cpu->ax = (uint16_t)(0x6);               /* mov ax, 0x6 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg152_0000(cpu);                        /* call 0000:FFFF */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4C)); /* les cx, word ss:[bp+-0x4C] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4C) + 2));
    push16(cpu, 0x12C);                      /* push 0x12C */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg152_00D6(cpu);                        /* call 0000:FFFF */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    goto L_seg179_0658_00087F;               /* jmp 0x087F */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x120);             /* mov bx, 0x120 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x118);             /* mov cx, 0x118 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:06A9 */ /* call 0000:06A9 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x123);             /* mov ax, 0x123 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x12B);             /* mov ax, 0x12B */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x121);             /* mov cx, 0x121 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:06C4 */ /* call 0000:06C4 */
L_seg179_0658_000748:;
L_seg179_0658_000748:;
    goto L_seg179_0658_0006C8;               /* jmp 0x06C8 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x142);             /* mov bx, 0x142 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x135);             /* mov cx, 0x135 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:0729 */ /* call 0000:0729 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x145);             /* mov ax, 0x145 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x152);             /* mov ax, 0x152 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x143);             /* mov cx, 0x143 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:0744 */ /* call 0000:0744 */
L_seg179_0658_00077C:;
L_seg179_0658_00077C:;
    goto L_seg179_0658_000748;               /* jmp 0x0748 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x164);             /* mov bx, 0x164 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x15C);             /* mov cx, 0x15C */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:075D */ /* call 0000:075D */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x167);             /* mov ax, 0x167 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x16F);             /* mov ax, 0x16F */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x165);             /* mov cx, 0x165 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:0778 */ /* call 0000:0778 */
L_seg179_0658_0007AF:;
L_seg179_0658_0007AF:;
    goto L_seg179_0658_000748;               /* jmp 0x0748 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x181);             /* mov bx, 0x181 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x179);             /* mov cx, 0x179 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:0790 */ /* call 0000:0790 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x184);             /* mov ax, 0x184 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x18C);             /* mov ax, 0x18C */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x182);             /* mov cx, 0x182 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:07AB */ /* call 0000:07AB */
L_seg179_0658_0007E2:;
L_seg179_0658_0007E2:;
    goto L_seg179_0658_00077C;               /* jmp 0x077C */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x1A2);             /* mov bx, 0x1A2 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x196);             /* mov cx, 0x196 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    /* unresolved far call call 0000:07C3 */ /* call 0000:07C3 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x1A5);             /* mov ax, 0x1A5 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x1B1);             /* mov ax, 0x1B1 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x1A3);             /* mov cx, 0x1A3 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:07DE */ /* call 0000:07DE */
    goto L_seg179_0658_0007AF;               /* jmp 0x07AF */
    push16(cpu, cpu->di);                    /* push di */
    cpu->bx = (uint16_t)(0x1C4);             /* mov bx, 0x1C4 */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->si = (uint16_t)((uint16_t)(cpu->si + 0x12)); /* lea si, word ds:[si+0x12] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->cx = (uint16_t)(0x1BB);             /* mov cx, 0x1BB */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg197_07F0(cpu);                        /* call 0000:07F6 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x1C7);             /* mov ax, 0x1C7 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(0x1D0);             /* mov ax, 0x1D0 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x1C5);             /* mov cx, 0x1C5 */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:0811 */ /* call 0000:0811 */
    goto L_seg179_0658_0007E2;               /* jmp 0x07E2 */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    cpu->cx = (uint16_t)(0x1DA);             /* mov cx, 0x1DA */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    /* unresolved far call call 0000:06F2 */ /* call 0000:06F2 */
    goto L_seg179_0658_0007E2;               /* jmp 0x07E2 */
L_seg179_0658_00085C:;
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg146_0000(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x8C)); /* lea ax, word ss:[bp+-0x8C] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg152_029E(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les ax, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x8C)); /* lea cx, word ss:[bp+-0x8C] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
L_seg179_0658_00087F:;
L_seg179_0658_00087F:;
    flags_cmp16(cpu, cpu->di, cpu->si);      /* cmp di, si */
    if (cc_l(cpu)) goto L_seg179_0658_00085C; /* jl 0x085C */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4C)); /* lea ax, word ss:[bp+-0x4C] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les ax, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
L_seg179_0658_000892:;
L_seg179_0658_000892:;
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

