/* Segment 181 - 2394 bytes, 6 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "cpu.h"
#include "fpu.h"
#include <math.h>

void seg181_0000(CPU *cpu);
void seg181_01CE(CPU *cpu);
void seg181_0514(CPU *cpu);
void seg181_0798(CPU *cpu);
void seg181_07FE(CPU *cpu);
void seg181_0876(CPU *cpu);

void seg181_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg205_0FE4(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(SEG_47);            /* mov ax, 0x4D  /* selector for seg47 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = mem_read16(cpu, cpu->es, 0x63); /* les ax, word es:[0x63] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x63 + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    if (cc_e(cpu)) goto L_seg181_0000_000026; /* je 0x0026 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    /* UNHANDLED: call far word ss:[bp+-0x4] */ /* call far word ss:[bp+-0x4] */
L_seg181_0000_000026:;
L_seg181_0000_000026:;
    cpu->ax = (uint16_t)(pop16(cpu));        /* pop ax */
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg181_01CE(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->es = (uint16_t)(cpu->cx);           /* mov es, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(0x64)); /* mov word ss:[bp+-0x2], 0x64 */
    cpu->bl = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x258))); /* mov bl, byte es:[bx+0x258] */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->si = (uint16_t)(cpu->bx);           /* mov si, bx */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    { uint16_t _r = cpu->bx & 0x7; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* and bx, 0x7 */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v >> _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (_c - 1)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shr bx, 0x1 */
    flags_cmp16(cpu, cpu->bx, 0x1);          /* cmp bx, 0x1 */
    if (cc_ae(cpu)) goto L_seg181_01CE_000263; /* jae 0x0263 */
    cpu->cx = (uint16_t)(0x19);              /* mov cx, 0x19 */
L_seg181_01CE_0001F8:;
L_seg181_01CE_0001F8:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xA)); /* les bx, word ss:[bp+0xA] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0xA) + 2));
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x10))); /* mov bx, word es:[bx+0x10] */
    { int16_t _v = (int16_t)cpu->bx; uint8_t _c = 0x1; int16_t _r = _v >> _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (_c - 1)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, (uint16_t)_r); cpu->bx = (uint16_t)((uint16_t)_r); } /* sar bx, 0x1 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x4], bx */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xA)); /* les bx, word ss:[bp+0xA] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0xA) + 2));
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x12))); /* mov bx, word es:[bx+0x12] */
    { int16_t _v = (int16_t)cpu->bx; uint8_t _c = 0x1; int16_t _r = _v >> _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (_c - 1)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, (uint16_t)_r); cpu->bx = (uint16_t)((uint16_t)_r); } /* sar bx, 0x1 */
    cpu->dx = (uint16_t)(SEG_24);            /* mov dx, 0x2FF  /* selector for seg24 */ */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->es, 0)); /* mov dx, word es:[0x0] */
    flags_logic8(cpu, cpu->ah & 0x1);        /* test ah, 0x1 */
    if (cc_e(cpu)) goto L_seg181_01CE_00026D; /* je 0x026D */
    cpu->dx = (uint16_t)(flags_add16(cpu, cpu->dx, 0xFFFC)); /* add dx, 0xFFFC */
    cpu->dx = (uint16_t)(flags_sub16(cpu, cpu->dx, cpu->cx)); /* sub dx, cx */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)cpu->dx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul dx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2)); cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv word ss:[bp+-0x2] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, cpu->cx)); /* add ax, cx */
L_seg181_01CE_00022B:;
L_seg181_01CE_00022B:;
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul word ss:[bp+-0x4] */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->bx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv bx */
    cpu->bx = (uint16_t)(0x3B5);             /* mov bx, 0x3B5 */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->ax = (uint16_t)(0x48);              /* mov ax, 0x48 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg186_015A(cpu);                        /* call 0000:001C */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); /* les bx, word ss:[bp+0x6] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x6) + 2));
    mem_write16(cpu, cpu->es, cpu->bx, (uint16_t)(cpu->ax)); /* mov word es:[bx], ax */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x2), (uint16_t)(cpu->dx)); /* mov word es:[bx+0x2], dx */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xA)); /* lds ax, word ss:[bp+0xA] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0xA) + 2));
    cpu->cx = mem_read16(cpu, cpu->es, cpu->bx); /* les cx, word es:[bx] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg206_015C(cpu);                        /* call 0000:FFFF */
    goto L_seg181_01CE_00028B;               /* jmp 0x028B */
L_seg181_01CE_000263:;
L_seg181_01CE_000263:;
    flags_cmp16(cpu, cpu->bx, 0x3);          /* cmp bx, 0x3 */
    if (cc_ae(cpu)) goto L_seg181_01CE_0001F8; /* jae 0x01F8 */
    cpu->cx = (uint16_t)(0x28);              /* mov cx, 0x28 */
    goto L_seg181_01CE_0001F8;               /* jmp 0x01F8 */
L_seg181_01CE_00026D:;
L_seg181_01CE_00026D:;
    cpu->ax = (uint16_t)(0xA);               /* mov ax, 0xA */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)cpu->dx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul dx */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0xFFD8)); /* add ax, 0xFFD8 */
    cpu->di = (uint16_t)(0xE);               /* mov di, 0xE */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->di; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv di */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, cpu->cx)); /* sub ax, cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)cpu->si; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul si */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2)); cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv word ss:[bp+-0x2] */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, cpu->cx)); /* add si, cx */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    goto L_seg181_01CE_00022B;               /* jmp 0x022B */
L_seg181_01CE_00028B:;
L_seg181_01CE_00028B:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0xC; return;                  /* retf 0x8 */
}

void seg181_0514(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x26)); /* sub sp, 0x26 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x4], cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x8], si */
    cpu->di = (uint16_t)(cpu->bx);           /* mov di, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x6], di */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(SEG_47);            /* mov ax, 0xFFFF  /* selector for seg47 */ */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, 0x6)); /* mov al, byte ds:[0x6] */
    flags_logic8(cpu, cpu->al & cpu->al);    /* test al, al */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x3201)) & cpu->dh); /* test byte ds:[si+0x3201], dh */
    { uint8_t _v = mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si + 0x6)); uint8_t _c = 0x83; uint8_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (8 - _c)) & 1 ? FLAG_CF : 0); flags_shift8(cpu, _r); mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si + 0x6), (uint8_t)(_r)); } /* shl byte ss:[bp+si+0x6], 0x83 */
    /* data byte: 0x66 */                    /* db 0x66 */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si)) & 0x8D); /* test byte ds:[bx+si], 0x8D */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x2)) & cpu->bl); /* test byte ds:[bx+si+0x2], bl */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xE], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0xC], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
    { uint16_t _r = cpu->ax & 0x7; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* and ax, 0x7 */
    { uint16_t _v = cpu->ax; uint8_t _c = 0x1; uint16_t _r = _v >> _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (_c - 1)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* shr ax, 0x1 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE)); /* lds ax, word ss:[bp+-0xE] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xE) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->si + 0x258)); /* lea cx, word ds:[si+0x258] */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x12], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x10], dx */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x83F);             /* mov ax, 0x83F */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = (uint16_t)(0x588);             /* mov ax, 0x588 */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, 0)); /* mov ax, word es:[0x0] */
    { uint16_t _v = cpu->ax; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* shl ax, 0x1 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 0xFFF8)); /* add cx, 0xFFF8 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0x2)); /* mov ax, word ds:[0x2] */
    { uint16_t _v = cpu->ax; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* shl ax, 0x1 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, 0xFFE6)); /* add bx, 0xFFE6 */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x16)); /* lea ax, word ss:[bp+-0x16] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE)); /* les ax, word ss:[bp+-0xE] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xE) + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12)); /* lds cx, word ss:[bp+-0x12] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x12) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg231_CA30(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x58D);             /* mov ax, 0x58D */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0xC)); /* mov ax, word ds:[0xC] */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)) | cpu->ax; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6), (uint16_t)(_r)); } /* or word ss:[bp+0x6], ax */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* push word ss:[bp+-0x14] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16))); /* push word ss:[bp+-0x16] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x1A)); /* lea ax, word ss:[bp+-0x1A] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov cx, word ss:[bp+-0x6] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_01CE(cpu);                        /* call 0x01CE */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint8_t _r = cpu->bl ^ cpu->bl; flags_logic8(cpu, _r); cpu->bl = (uint8_t)(_r); } /* xor bl, bl */
    cpu->ax = (uint16_t)(0x61A8);            /* mov ax, 0x61A8 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x1E], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x1C], dx */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x61A8);                     /* push 0x61A8 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E)); /* les ax, word ss:[bp+-0x1E] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x1E) + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16)); /* lds cx, word ss:[bp+-0x16] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x16) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint8_t _r = cpu->bl ^ cpu->bl; flags_logic8(cpu, _r); cpu->bl = (uint8_t)(_r); } /* xor bl, bl */
    cpu->ax = (uint16_t)(0x61A8);            /* mov ax, 0x61A8 */
    /* unresolved far call call 0000:05EE */ /* call 0000:05EE */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x22), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x22], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x20], dx */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x61A8);                     /* push 0x61A8 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x22)); /* les ax, word ss:[bp+-0x22] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x22) + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A)); /* lds cx, word ss:[bp+-0x1A] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x1A) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:0612 */ /* call 0000:0612 */
    cpu->si = (uint16_t)(0x0);               /* mov si, 0x0 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E)); /* lds bx, word ss:[bp+-0x1E] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x1E) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 0x5F8)); /* add cx, 0x5F8 */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 0x0 + cf(cpu))); /* adc si, 0x0 */
    cpu->dx = (uint16_t)(0x0);               /* mov dx, 0x0 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x22)); /* lds bx, word ss:[bp+-0x22] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x22) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, cpu->ax)); /* add cx, ax */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, cpu->dx + cf(cpu))); /* adc si, dx */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 0x1F4)); /* add cx, 0x1F4 */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 0x0 + cf(cpu))); /* adc si, 0x0 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8)); /* lds ax, word ss:[bp+0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x8) + 2));
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    flags_cmp16(cpu, cpu->dx, cpu->si);      /* cmp dx, si */
    if (cc_l(cpu)) goto L_seg181_0514_000680; /* jl 0x0680 */
    if (cc_g(cpu)) goto L_seg181_0514_0006F9; /* jg 0x06F9 */
    flags_cmp16(cpu, cpu->ax, cpu->cx);      /* cmp ax, cx */
    if (cc_ae(cpu)) goto L_seg181_0514_0006F9; /* jae 0x06F9 */
L_seg181_0514_000680:;
L_seg181_0514_000680:;
    cpu->ax = (uint16_t)(0x4D);              /* mov ax, 0x4D */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg137_0072(cpu);                        /* call 0000:FFFF */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    cpu->dx = (uint16_t)(0xFFFF);            /* mov dx, 0xFFFF */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->es);                    /* push es */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->ax = (uint16_t)(0x68F);             /* mov ax, 0x68F */
    push16(cpu, cpu->ax);                    /* push ax */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x10)); /* add sp, 0x10 */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->ax = (uint16_t)(0x68F);             /* mov ax, 0x68F */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x280);                      /* push 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_08AA(cpu);                        /* call 0000:0010 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(0x1)); /* mov word ss:[bp+-0xA], 0x1 */
L_seg181_0514_0006B2:;
L_seg181_0514_0006B2:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x1E)); /* lea ax, word ss:[bp+-0x1E] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x22)); /* lea ax, word ss:[bp+-0x22] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:06B8 */ /* call 0000:06B8 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x1A)); /* lea ax, word ss:[bp+-0x1A] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x16)); /* lea ax, word ss:[bp+-0x16] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:06CC */ /* call 0000:06CC */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x12)); /* lea ax, word ss:[bp+-0x12] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0xE)); /* lea ax, word ss:[bp+-0xE] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg230_2292(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ax, word ss:[bp+-0xA] */
    goto L_seg181_0514_000791;               /* jmp 0x0791 */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* jmp out of function to 0x000542 */    /* jmp 0x0542 */
L_seg181_0514_0006F9:;
L_seg181_0514_0006F9:;
    push16(cpu, 0xFFFF);                     /* push 0xFFFF */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8)); /* lds cx, word ss:[bp+0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x8) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x26], bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x24), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x24], ds */
    cpu->cx = (uint16_t)(0x0);               /* mov cx, 0x0 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2C3)) | cpu->ax; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2C3), (uint16_t)(_r)); } /* or word ds:[bx+0x2C3], ax */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2C5)) | cpu->cx; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2C5), (uint16_t)(_r)); } /* or word ds:[bx+0x2C5], cx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* mov ax, word ss:[bp+0x6] */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x3DC)) | cpu->ax; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x3DC), (uint16_t)(_r)); } /* or word ds:[bx+0x3DC], ax */
    push16(cpu, 0x3);                        /* push 0x3 */
    push16(cpu, 0x5F8);                      /* push 0x5F8 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov cx, word ss:[bp+-0x8] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov dx, word ss:[bp+-0x6] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds ax, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds ax, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    push16(cpu, 0x6);                        /* push 0x6 */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x22)); /* les cx, word ss:[bp+-0x22] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x22) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds ax, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds ax, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    push16(cpu, 0x5);                        /* push 0x5 */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E)); /* les cx, word ss:[bp+-0x1E] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x1E) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:074F */ /* call 0000:074F */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x26)); /* lea ax, word ss:[bp+-0x26] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_0216(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov ax, word ss:[bp+-0x4] */
    { uint16_t _r = cpu->cx | cpu->ax; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* or cx, ax */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di)) & cpu->dh); /* test byte ss:[bp+di], dh */
    { int _cf = cf(cpu); cpu->bp = (uint16_t)(flags_add16(cpu, cpu->bp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc bp */
    /* jbe out of function to 0x000764 */    /* jbe 0x0764 */
    push16(cpu, mem_read16(cpu, cpu->ds, cpu->si)); /* push word ds:[si] */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E)); /* lds cx, word ss:[bp+-0x1E] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x1E) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    goto L_seg181_0514_0006B2;               /* jmp 0x06B2 */
L_seg181_0514_000791:;
L_seg181_0514_000791:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0xA; return;                  /* retf 0x6 */
}

void seg181_0798(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0xA)); /* sub sp, 0xA */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    cpu->ax = (uint16_t)(cpu->es);           /* mov ax, es */
    { uint16_t _r = cpu->ax | cpu->si; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, si */
    if (cc_e(cpu)) goto L_seg181_0798_0007F7; /* je 0x07F7 */
    cpu->bx = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xE4)); /* lds bx, word es:[si+0xE4] */
    cpu->ds = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xE4) + 2));
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->bx; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, bx */
    if (cc_e(cpu)) goto L_seg181_0798_0007F7; /* je 0x07F7 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x58))); /* mov ax, word ds:[bx+0x58] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6], ax */
    cpu->ax = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xEC)); /* lds ax, word es:[si+0xEC] */
    cpu->ds = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xEC) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    if (cc_e(cpu)) goto L_seg181_0798_0007F7; /* je 0x07F7 */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    goto L_seg181_0798_0007E6;               /* jmp 0x07E6 */
L_seg181_0798_0007D4:;
L_seg181_0798_0007D4:;
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di), (uint8_t)(0x0)); /* mov byte ds:[bx+di], 0x0 */
    { uint8_t _r = cpu->dl ^ cpu->dl; flags_logic8(cpu, _r); cpu->dl = (uint8_t)(_r); } /* xor dl, dl */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg214_08A2(cpu);                        /* call 0000:FFFF */
L_seg181_0798_0007E5:;
L_seg181_0798_0007E5:;
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
L_seg181_0798_0007E6:;
L_seg181_0798_0007E6:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    flags_cmp16(cpu, cpu->di, cpu->ax);      /* cmp di, ax */
    if (cc_ge(cpu)) goto L_seg181_0798_0007F7; /* jge 0x07F7 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov bx, word ss:[bp+-0xA] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di)), 0x0); /* cmp byte ds:[bx+di], 0x0 */
    if (cc_ne(cpu)) goto L_seg181_0798_0007D4; /* jne 0x07D4 */
    goto L_seg181_0798_0007E5;               /* jmp 0x07E5 */
L_seg181_0798_0007F7:;
L_seg181_0798_0007F7:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg181_07FE(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x6)); /* sub sp, 0x6 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    { uint8_t _r = cpu->bl ^ cpu->bl; flags_logic8(cpu, _r); cpu->bl = (uint8_t)(_r); } /* xor bl, bl */
    cpu->ax = (uint16_t)(0x3);               /* mov ax, 0x3 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg159_0368(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x6)); /* lea ax, word ss:[bp+-0x6] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD0))); /* mov ax, word ds:[si+0xD0] */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD4)))); /* sub ax, word ds:[si+0xD4] */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg214_06E4(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(0x83A);             /* mov ax, 0x83A */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->bx = (uint16_t)(0x2);               /* mov bx, 0x2 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->bx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv bx */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)))); /* add ax, word ss:[bp+-0x4] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->bx = (uint16_t)(0x2);               /* mov bx, 0x2 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, 0x2)); /* mov ax, word es:[0x2] */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->bx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv bx */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)))); /* add ax, word ss:[bp+-0x6] */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x11);                       /* push 0x11 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); /* lds ax, word ss:[bp+0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x6) + 2));
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov dx, word ss:[bp+-0x2] */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_368C(cpu);                        /* call 0000:FFFF */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0x8; return;                  /* retf 0x4 */
}

void seg181_0876(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0302(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0230(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg196_0B8A(cpu);                        /* call 0000:FFFF */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    flags_cmp16(cpu, cpu->bx, 0x5);          /* cmp bx, 0x5 */
    if (cc_ae(cpu)) goto L_seg181_0876_0008CB; /* jae 0x08CB */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shl bx, 0x1 */
    /* indirect jmp via mem_read16(cpu, cpu->cs, (uint16_t)(cpu->bx + 0x950)) - needs dispatch */ /* jmp word cs:[bx+0x950] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_0174(cpu);                        /* call 0x0174 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->ax = (uint16_t)(0x2A);              /* mov ax, 0x2A */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les ax, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg180_0590(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_01C8(cpu);                        /* call 0x01C8 */
L_seg181_0876_0008CB:;
L_seg181_0876_0008CB:;
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    /* unresolved far call call 0000:08B4 */ /* call 0000:08B4 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_01D2(cpu);                        /* call 0000:0896 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0184(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg205_0E12(cpu);                        /* call 0000:FFFF */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg205_0338(cpu);                        /* call 0000:FFFF */
    goto L_seg181_0876_00094B;               /* jmp 0x094B */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_0174(cpu);                        /* call 0x0174 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->ax = (uint16_t)(0x2C);              /* mov ax, 0x2C */
    /* unresolved far call call 0000:08CE */ /* call 0000:08CE */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les ax, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg193_06A6(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_01C8(cpu);                        /* call 0x01C8 */
    goto L_seg181_0876_0008CB;               /* jmp 0x08CB */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_0174(cpu);                        /* call 0x0174 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->ax = (uint16_t)(0x2D);              /* mov ax, 0x2D */
    /* unresolved far call call 0000:08FC */ /* call 0000:08FC */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les ax, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg199_08B6(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg181_01C8(cpu);                        /* call 0x01C8 */
    goto L_seg181_0876_0008CB;               /* jmp 0x08CB */
    cpu->ax = (uint16_t)(0x30);              /* mov ax, 0x30 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg196_0510(cpu);                        /* call 0000:0923 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg210_0FF8(cpu);                        /* call 0000:FFFF */
    goto L_seg181_0876_0008CB;               /* jmp 0x08CB */
L_seg181_0876_00094B:;
L_seg181_0876_00094B:;
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

