/* Segment 159 - 1216 bytes, 4 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "cpu.h"
#include "fpu.h"
#include <math.h>

void seg159_0000(CPU *cpu);
void seg159_0078(CPU *cpu);
void seg159_0368(CPU *cpu);
void seg159_03F6(CPU *cpu);

void seg159_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8)); /* sub sp, 0x8 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x4], cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x6], bx */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    if (cc_ne(cpu)) goto L_seg159_0000_00001E; /* jne 0x001E */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg159_0000_000073;               /* jmp 0x0073 */
L_seg159_0000_00001E:;
L_seg159_0000_00001E:;
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x14);              /* mov ax, 0x14 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_0000(cpu);                        /* call 0000:046C */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->si; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, si */
    if (cc_ne(cpu)) goto L_seg159_0000_000037; /* jne 0x0037 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg159_0000_000073;               /* jmp 0x0073 */
L_seg159_0000_000037:;
    cpu->ax = (uint16_t)(SEG_70);            /* mov ax, 0x93  /* selector for seg70 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = (uint16_t)(cpu->si);           /* lea ax, word ds:[si] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov di, word ss:[bp+-0x2] */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    cpu->cx = mem_read16(cpu, cpu->es, cpu->di); /* les cx, word es:[di] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(cpu->di + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg153_0000(cpu);                        /* call 0000:0497 */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x8), (uint8_t)(0x0)); /* mov byte ds:[si+0x8], 0x0 */
    cpu->bx = (uint16_t)(0x0);               /* mov bx, 0x0 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov ax, word ss:[bp+-0x4] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x9), (uint16_t)(cpu->ax)); /* mov word ds:[si+0x9], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB), (uint16_t)(cpu->bx)); /* mov word ds:[si+0xB], bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov ax, word ss:[bp+-0x8] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE), (uint16_t)(cpu->ax)); /* mov word ds:[si+0xE], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x10), (uint16_t)(cpu->ax)); /* mov word ds:[si+0x10], ax */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
L_seg159_0000_000073:;
L_seg159_0000_000073:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg159_0078(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x3C6)); /* sub sp, 0x3C6 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_0032(cpu);                        /* call 0000:01D1 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_005E(cpu);                        /* call 0000:01D6 */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    cpu->bx = (uint16_t)(0x191);             /* mov bx, 0x191 */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg159_0078_0000CA; /* jne 0x00CA */
L_seg159_0078_00009E:;
L_seg159_0078_00009E:;
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
L_seg159_0078_0000A0:;
L_seg159_0078_0000A0:;
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shl bx, 0x1 */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shl bx, 0x1 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ds, word ss:[bp+-0x2] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x1D4), (uint16_t)(cpu->di)); /* mov word ds:[bx+0x1D4], di */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x1D6), (uint16_t)(cpu->di)); /* mov word ds:[bx+0x1D6], di */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    flags_cmp16(cpu, cpu->ax, 0x5);          /* cmp ax, 0x5 */
    if (cc_l(cpu)) goto L_seg159_0078_0000A0; /* jl 0x00A0 */
L_seg159_0078_0000B7:;
L_seg159_0078_0000B7:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C4)); /* lea ax, word ss:[bp+-0x3C4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_0416(cpu);                        /* call 0000:02F5 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_0050(cpu);                        /* call 0000:02FA */
    goto L_seg159_0078_00017A;               /* jmp 0x017A */
L_seg159_0078_0000CA:;
L_seg159_0078_0000CA:;
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x48), (uint8_t)(0x0)); /* mov byte ss:[bp+-0x48], 0x0 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0xE8);              /* mov ax, 0xE8 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0xF0);              /* mov ax, 0xF0 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea ax, word ss:[bp+-0x48] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0xE2);              /* mov cx, 0xE2 */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg173_0572(cpu);                        /* call 0000:023D */
    cpu->ax = (uint16_t)(SEG_50);            /* mov ax, 0x242  /* selector for seg50 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    { uint16_t _r = mem_read16(cpu, cpu->es, 0x88) | 0xFFFF; flags_logic16(cpu, _r); mem_write16(cpu, cpu->es, 0x88, (uint16_t)(_r)); } /* or word es:[0x88], 0xFFFF */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C4)); /* lea ax, word ss:[bp+-0x3C4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x48)); /* lea cx, word ss:[bp+-0x48] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_0162(cpu);                        /* call 0000:025A */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg159_0078_00009E; /* jne 0x009E */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x3C6), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x3C6], di */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x343))); /* push word ss:[bp+-0x343] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x345))); /* push word ss:[bp+-0x345] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C6)); /* lea ax, word ss:[bp+-0x3C6] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C4)); /* lea ax, word ss:[bp+-0x3C4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(0x1E8);             /* mov cx, 0x1E8 */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    /* unresolved far call call 0000:02C2 */ /* call 0000:02C2 */
L_seg159_0078_00012C:;
L_seg159_0078_00012C:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x3C6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x3C6], ax */
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1EA))); /* push word ds:[si+0x1EA] */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1E8))); /* push word ds:[si+0x1E8] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C6)); /* lea ax, word ss:[bp+-0x3C6] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x3C4)); /* lea ax, word ss:[bp+-0x3C4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_06B4(cpu);                        /* call 0000:0128 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x3C6))); /* mov ax, word ss:[bp+-0x3C6] */
    cpu->dx = (uint16_t)(cpu->di);           /* mov dx, di */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg159_0000(cpu);                        /* call 0x0000 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4), (uint16_t)(cpu->ax)); /* mov word ds:[si+0x1D4], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D6), (uint16_t)(cpu->dx)); /* mov word ds:[si+0x1D6], dx */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    flags_cmp16(cpu, cpu->di, 0x5);          /* cmp di, 0x5 */
    if (cc_l(cpu)) goto L_seg159_0078_00012C; /* jl 0x012C */
    goto L_seg159_0078_0000B7;               /* jmp 0x00B7 */
L_seg159_0078_00017A:;
L_seg159_0078_00017A:;
    cpu->ax = (uint16_t)(pop16(cpu));        /* pop ax */
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg159_0368(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1), (uint8_t)(cpu->cl)); /* mov byte ss:[bp+-0x1], cl */
    cpu->dl = (uint8_t)(cpu->bl);            /* mov dl, bl */
    cpu->bx = (uint16_t)(0x427);             /* mov bx, 0x427 */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4)); /* les ax, word ds:[si+0x1D4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x1D4) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    if (cc_e(cpu)) goto L_seg159_0368_0003F0; /* je 0x03F0 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(SEG_91);            /* mov ax, 0xFFFF  /* selector for seg91 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, 0x518), 0x0); /* cmp byte es:[0x518], 0x0 */
    if (cc_e(cpu)) goto L_seg159_0368_0003EB; /* je 0x03EB */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg159_0368_0003EB; /* je 0x03EB */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_01C4(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4)); /* les ax, word ds:[si+0x1D4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x1D4) + 2));
    cpu->cx = (uint16_t)(0x8);               /* mov cx, 0x8 */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4)); /* les bx, word ds:[si+0x1D4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x1D4) + 2));
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4)); /* les ax, word ds:[si+0x1D4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x1D4) + 2));
    cpu->cl = (uint8_t)(cpu->dl);            /* mov cl, dl */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_00FA(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x1D4)); /* lds ax, word ds:[si+0x1D4] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0x1D4) + 2));
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_03DA(cpu);                        /* call 0000:03B7 */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1)), 0x0); /* cmp byte ss:[bp+-0x1], 0x0 */
    if (cc_e(cpu)) goto L_seg159_0368_0003EB; /* je 0x03EB */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_0518(cpu);                        /* call 0000:FFFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg159_0368_0003EB:;
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg159_0368_0003F0:;
L_seg159_0368_0003F0:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg159_03F6(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    flags_cmp16(cpu, cpu->cx, 0x8);          /* cmp cx, 0x8 */
    if (cc_l(cpu)) goto L_seg159_03F6_000411; /* jl 0x0411 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(_r)); } /* and word ss:[bp+-0x2], 0x0 */
L_seg159_03F6_00040C:;
L_seg159_03F6_00040C:;
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov dx, word ss:[bp+-0x2] */
    goto L_seg159_03F6_000442;               /* jmp 0x0442 */
L_seg159_03F6_000411:;
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg198_054C(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg198_04A1(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ax = (uint16_t)(0x3);               /* mov ax, 0x3 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->bx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv bx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->dx); cpu->dx = (uint16_t)(_t); } /* xchg ax, dx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->ax = (uint16_t)(0x480);             /* mov ax, 0x480 */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = (uint16_t)(0xC);               /* mov ax, 0xC */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->cx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul cx */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shl bx, 0x1 */
    { uint16_t _v = cpu->bx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* shl bx, 0x1 */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, cpu->bx)); /* add si, bx */
    cpu->ax = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x114)); /* les ax, word es:[si+0x114] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0x114) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    goto L_seg159_03F6_00040C;               /* jmp 0x040C */
L_seg159_03F6_000442:;
L_seg159_03F6_000442:;
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

