/* Segment 171 - 1763 bytes, 3 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "segments.h"

void seg171_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0xA)); /* sub sp, 0xA */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x4], bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6], ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0202(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8))); /* mov ax, word ss:[bp+0x8] */
    { uint16_t _r = cpu->ax | mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, word ss:[bp+0x6] */
    if (cc_ne(cpu)) goto L_seg171_0000_000023; /* jne 0x0023 */
L_seg171_0000_00001F:;
L_seg171_0000_00001F:;
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    goto L_seg171_0000_00002E;               /* jmp 0x002E */
L_seg171_0000_000023:;
L_seg171_0000_000023:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); /* lds bx, word ss:[bp+0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x6) + 2));
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, cpu->bx), 0x0); /* cmp byte ds:[bx], 0x0 */
    if (cc_e(cpu)) goto L_seg171_0000_00001F; /* je 0x001F */
    cpu->di = (uint16_t)(0x40);              /* mov di, 0x40 */
L_seg171_0000_00002E:;
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg185_0000(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xA], bx */
    cpu->si = (uint16_t)(cpu->dx);           /* mov si, dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* push word ss:[bp+-0x2] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x10))); /* mov ax, word ss:[bp+0x10] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x8)); /* add ax, 0x8 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xE))); /* mov ax, word ss:[bp+0xE] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x8)); /* add ax, 0x8 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x1);                        /* push 0x1 */
    { uint16_t _r = cpu->di | 0x84; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* or di, 0x84 */
    push16(cpu, cpu->di);                    /* push di */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov dx, word ss:[bp+-0x4] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov cx, word ss:[bp+-0x6] */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_2530(cpu);                        /* call 0000:FFFF */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    cpu->dx = (uint16_t)(0x4);               /* mov dx, 0x4 */
    cpu->cx = (uint16_t)(0x1);               /* mov cx, 0x1 */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_42F2(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_2B96(cpu);                        /* call 0000:FFFF */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8))); /* push word ss:[bp+0x8] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* push word ss:[bp+0x6] */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_32C2(cpu);                        /* call 0000:0016 */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->di; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, di */
    if (cc_ne(cpu)) goto L_seg171_0000_0000A9; /* jne 0x00A9 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ax, word ss:[bp+-0xA] */
    { uint16_t _r = cpu->si | cpu->ax; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* or si, ax */
    if (cc_e(cpu)) goto L_seg171_0000_0000A3; /* je 0x00A3 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg185_00A2(cpu);                        /* call 0000:0182 */
L_seg171_0000_0000A3:;
L_seg171_0000_0000A3:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg171_0000_000141;               /* jmp 0x0141 */
L_seg171_0000_0000A9:;
L_seg171_0000_0000A9:;
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xA)); /* les ax, word ss:[bp+0xA] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0xA) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xAC), (uint16_t)(cpu->ax)); /* mov word ds:[di+0xAC], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xAE), (uint16_t)(cpu->es)); /* mov word ds:[di+0xAE], es */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x8), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x8)), 0x3))); /* add word ds:[di+0x8], 0x3 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xC), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xC)), 0x3))); /* add word ds:[di+0xC], 0x3 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x10))); /* mov ax, word ss:[bp+0x10] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x10), (uint16_t)(cpu->ax)); /* mov word ds:[di+0x10], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xE))); /* mov ax, word ss:[bp+0xE] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x12), (uint16_t)(cpu->ax)); /* mov word ds:[di+0x12], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x10))); /* mov ax, word ss:[bp+0x10] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xE))); /* mov bx, word ss:[bp+0xE] */
    cpu->cl = (uint8_t)(0xFF);               /* mov cl, 0xFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xB0), (uint16_t)(cpu->ax)); /* mov word ds:[di+0xB0], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xB2), (uint16_t)(cpu->dx)); /* mov word ds:[di+0xB2], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x10))); /* mov ax, word ss:[bp+0x10] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0xE))); /* mov bx, word ss:[bp+0xE] */
    cpu->cl = (uint8_t)(0xFF);               /* mov cl, 0xFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_3CAC(cpu);                        /* call 0000:00D1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xE0), (uint16_t)(cpu->ax)); /* mov word ds:[di+0xE0], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xE2), (uint16_t)(cpu->dx)); /* mov word ds:[di+0xE2], dx */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xB0)); /* les ax, word ds:[di+0xB0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->di + 0xB0) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_3D08(cpu);                        /* call 0000:FFFF */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xB4), (uint16_t)(cpu->ax)); /* mov word ds:[di+0xB4], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xB6), (uint16_t)(cpu->dx)); /* mov word ds:[di+0xB6], dx */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x10))); /* push word ds:[di+0x10] */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x12))); /* push word ds:[di+0x12] */
    push16(cpu, 0xFFFF);                     /* push 0xFFFF */
    cpu->si = (uint16_t)((uint16_t)(cpu->di + 0x1D)); /* lea si, word ds:[di+0x1D] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x8))); /* mov ax, word ds:[di+0x8] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->ds, cpu->di))); /* add ax, word ds:[di] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0xC))); /* mov dx, word ds:[di+0xC] */
    cpu->dx = (uint16_t)(flags_add16(cpu, cpu->dx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di + 0x2)))); /* add dx, word ds:[di+0x2] */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_20BE(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(SEG_12);            /* mov ax, 0x313  /* selector for seg12 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, 0x8), 0x0); /* cmp byte es:[0x8], 0x0 */
    if (cc_ne(cpu)) goto L_seg171_0000_00013D; /* jne 0x013D */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0302(cpu);                        /* call 0000:055B */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0230(cpu);                        /* call 0000:FFFF */
L_seg171_0000_00013D:;
L_seg171_0000_00013D:;
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
L_seg171_0000_000141:;
L_seg171_0000_000141:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0x10; return;                 /* retf 0xC */
}

void seg171_0148(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->si; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, si */
    if (cc_e(cpu)) goto L_seg171_0148_000186; /* je 0x0186 */
    cpu->di = mem_read16(cpu, cpu->ds, cpu->si); /* lds di, word ds:[si] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->di + 0xE0)); /* lea ax, word ds:[di+0xE0] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->di + 0xB0)); /* lea ax, word ds:[di+0xB0] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_00C0(cpu);                        /* call 0000:0168 */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_2C90(cpu);                        /* call 0000:FFFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg171_0148_000186:;
L_seg171_0148_000186:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg171_018C(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x12)); /* sub sp, 0x12 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, cpu->si)); /* mov ax, word es:[si] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x8)))); /* add ax, word es:[si+0x8] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x2], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x2))); /* mov ax, word es:[si+0x2] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xC)))); /* add ax, word es:[si+0xC] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    cpu->bx = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xE0)); /* lds bx, word es:[si+0xE0] */
    cpu->ds = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xE0) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x8], bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x12))); /* mov ax, word ds:[bx+0x12] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x10))); /* mov ax, word ds:[bx+0x10] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xC], ax */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xF4))); /* mov di, word es:[si+0xF4] */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xE], bx */
    goto L_seg171_018C_0001DF;               /* jmp 0x01DF */
L_seg171_018C_0001D2:;
L_seg171_018C_0001D2:;
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
L_seg171_018C_0001D4:;
L_seg171_018C_0001D4:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov bx, word ss:[bp+-0xE] */
    { int _cf = cf(cpu); cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xE], bx */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
L_seg171_018C_0001DF:;
L_seg171_018C_0001DF:;
    flags_cmp16(cpu, cpu->bx, cpu->ax);      /* cmp bx, ax */
    if (cc_ge(cpu)) goto L_seg171_018C_00021C; /* jge 0x021C */
    cpu->ax = (uint16_t)(SEG_99);            /* mov ax, 0xFFFF  /* selector for seg99 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = mem_read16(cpu, cpu->es, 0x655); /* les ax, word es:[0x655] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x655 + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x12], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x10], es */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* push word ss:[bp+-0xA] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov bx, word ss:[bp+-0x8] */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2A)); /* les bx, word ds:[bx+0x2A] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0x2A) + 2));
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->ax = mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si)); /* les ax, word es:[bx+si] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->bx + cpu->si) + 2));
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov si, word ss:[bp+-0x4] */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov cx, word ss:[bp+-0x2] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* UNHANDLED: call far word ss:[bp+-0x12] */ /* call far word ss:[bp+-0x12] */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov ax, word ss:[bp+-0xC] */
    flags_cmp16(cpu, cpu->di, cpu->ax);      /* cmp di, ax */
    if (cc_ge(cpu)) goto L_seg171_018C_0001D2; /* jge 0x01D2 */
    goto L_seg171_018C_0001D4;               /* jmp 0x01D4 */
L_seg171_018C_00021C:;
L_seg171_018C_00021C:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

