/* Segment 201 - 3673 bytes, 6 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "segments.h"

void seg201_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x70)); /* sub sp, 0x70 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x6], bx */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x1006);            /* mov ax, 0x1006 */
    /* unresolved far call call 0000:0442 */ /* call 0000:0442 */
    cpu->bx = (uint16_t)(SEG_74);            /* mov bx, 0x223  /* selector for seg74 */ */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0xA], es */
    mem_write16(cpu, cpu->es, 0x22C, (uint16_t)(cpu->ax)); /* mov word es:[0x22C], ax */
    mem_write16(cpu, cpu->es, 0x22E, (uint16_t)(cpu->dx)); /* mov word es:[0x22E], dx */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0xC], di */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x40)); /* lea ax, word ds:[si+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)(0xC);               /* mov cx, 0xC */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_09E2(cpu);                        /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg201_0000_0000C4; /* je 0x00C4 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(0x14)); /* mov word ss:[bp+-0xE], 0x14 */
    goto L_seg201_0000_0000B3;               /* jmp 0x00B3 */
L_seg201_0000_000052:;
L_seg201_0000_000052:;
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0xE)); /* lea ax, word ss:[bp+-0xE] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x40)); /* lea ax, word ds:[si+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x22)); /* lea cx, word ss:[bp+-0x22] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_06B4(cpu);                        /* call 0000:05CF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x40)); /* lea ax, word ds:[si+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_0A3C(cpu);                        /* call 0000:FFFF */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov es, word ss:[bp+-0xA] */
    cpu->bx = mem_read16(cpu, cpu->es, 0x22C); /* les bx, word es:[0x22C] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x22C + 2));
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->si; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, cl */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x16), (uint8_t)(0x1)); /* mov byte es:[bx+si+0x16], 0x1 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov ax, word ss:[bp+-0x14] */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x18), (uint16_t)(cpu->ax)); /* mov word es:[bx+si+0x18], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov ax, word ss:[bp+-0x12] */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x1A), (uint16_t)(cpu->ax)); /* mov word es:[bx+si+0x1A], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x1C), (uint16_t)(cpu->ax)); /* mov word es:[bx+si+0x1C], ax */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x13), (uint16_t)(0x1)); /* mov word es:[bx+si+0x13], 0x1 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x6)); /* lea ax, word ds:[bx+si+0x6] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x22)); /* lea cx, word ss:[bp+-0x22] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg153_0000(cpu);                        /* call 0000:0B3B */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0xC], di */
L_seg201_0000_0000B3:;
L_seg201_0000_0000B3:;
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov si, word ss:[bp+-0x4] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x8E))); /* mov ax, word ds:[si+0x8E] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x90))); /* mov cx, word ds:[si+0x90] */
    cpu->bx = (uint16_t)(cpu->cx);           /* mov bx, cx */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    if (cc_ne(cpu)) goto L_seg201_0000_000052; /* jne 0x0052 */
L_seg201_0000_0000C4:;
L_seg201_0000_0000C4:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x8), (uint16_t)(cpu->di)); /* mov word ds:[bx+0x8], di */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x1002);            /* mov ax, 0x1002 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_0000(cpu);                        /* call 0000:001F */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x26], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x24), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x24], dx */
    push16(cpu, 0xB);                        /* push 0xB */
    push16(cpu, 0x1002);                     /* push 0x1002 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x40)); /* lea ax, word ds:[si+0x40] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds cx, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x28], di */
    goto L_seg201_0000_00015E;               /* jmp 0x015E */
L_seg201_0000_0000F6:;
L_seg201_0000_0000F6:;
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->di; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, cl */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2A), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x2A], di */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ds, word ss:[bp+-0xA] */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x1AE);             /* mov ax, 0x1AE */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x70)); /* lea ax, word ss:[bp+-0x70] */
    cpu->si = (uint16_t)(cpu->ss);           /* mov si, ss */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* les bx, word ss:[bp+-0x26] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x2)); /* lea cx, word ds:[bx+di+0x2] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x70)); /* lea ax, word ss:[bp+-0x70] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:0398 */ /* call 0000:0398 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg201_0000_000157; /* je 0x0157 */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x22C); /* lds bx, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov si, word ss:[bp+-0xC] */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->si; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, cl */
    push16(cpu, 0x20);                       /* push 0x20 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x6)); /* lea ax, word ds:[bx+si+0x6] */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* les bx, word ss:[bp+-0x26] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2A))); /* mov di, word ss:[bp+-0x2A] */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x2)); /* lea cx, word ds:[bx+di+0x2] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ds, word ss:[bp+-0xA] */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x22C); /* lds bx, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x16), (uint8_t)(0x1)); /* mov byte ds:[bx+si+0x16], 0x1 */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ss:[bp+-0xC] */
L_seg201_0000_000157:;
L_seg201_0000_000157:;
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28))); /* mov di, word ss:[bp+-0x28] */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x28], di */
L_seg201_0000_00015E:;
L_seg201_0000_00015E:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds bx, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), cpu->di); /* cmp word ds:[bx], di */
    if (cc_le(cpu)) goto L_seg201_0000_00016C; /* jle 0x016C */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)), 0x80); /* cmp word ss:[bp+-0xC], 0x80 */
    if (cc_l(cpu)) goto L_seg201_0000_0000F6; /* jl 0x00F6 */
L_seg201_0000_00016C:;
L_seg201_0000_00016C:;
    push16(cpu, 0xA);                        /* push 0xA */
    push16(cpu, 0x1002);                     /* push 0x1002 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds cx, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_07B6(cpu);                        /* call 0000:00EB */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x28], di */
L_seg201_0000_000189:;
L_seg201_0000_000189:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* lds bx, word ss:[bp+-0x26] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), cpu->di); /* cmp word ds:[bx], di */
    if (cc_le(cpu)) goto L_seg201_0000_000197; /* jle 0x0197 */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)), 0x80); /* cmp word ss:[bp+-0xC], 0x80 */
    if (cc_l(cpu)) goto L_seg201_0000_0001B0; /* jl 0x01B0 */
L_seg201_0000_000197:;
L_seg201_0000_000197:;
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ds, word ss:[bp+-0xA] */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x22C); /* lds bx, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov ax, word ss:[bp+-0xC] */
    mem_write16(cpu, cpu->ds, cpu->bx, (uint16_t)(cpu->ax)); /* mov word ds:[bx], ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x26)); /* lea ax, word ss:[bp+-0x26] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg138_00C0(cpu);                        /* call 0000:0229 */
    goto L_seg201_0000_00021B;               /* jmp 0x021B */
L_seg201_0000_0001B0:;
L_seg201_0000_0001B0:;
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->di; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, cl */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2A), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x2A], di */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ds, word ss:[bp+-0xA] */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x1B2);             /* mov ax, 0x1B2 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x70)); /* lea ax, word ss:[bp+-0x70] */
    cpu->si = (uint16_t)(cpu->ss);           /* mov si, ss */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* les bx, word ss:[bp+-0x26] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x2)); /* lea cx, word ds:[bx+di+0x2] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg197_0B06(cpu);                        /* call 0000:0115 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x70)); /* lea ax, word ss:[bp+-0x70] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg139_0060(cpu);                        /* call 0000:011F */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg201_0000_000211; /* je 0x0211 */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x22C); /* lds bx, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov di, word ss:[bp+-0xC] */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->di; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, cl */
    push16(cpu, 0x20);                       /* push 0x20 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x6)); /* lea ax, word ds:[bx+di+0x6] */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x26)); /* les bx, word ss:[bp+-0x26] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x26) + 2));
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2A))); /* mov si, word ss:[bp+-0x2A] */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x2)); /* lea cx, word ds:[bx+si+0x2] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg153_02AC(cpu);                        /* call 0000:0145 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ds, word ss:[bp+-0xA] */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x22C); /* lds bx, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x16), (uint8_t)(0x2)); /* mov byte ds:[bx+di+0x16], 0x2 */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ss:[bp+-0xC] */
L_seg201_0000_000211:;
L_seg201_0000_000211:;
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28))); /* mov di, word ss:[bp+-0x28] */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x28), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x28], di */
    goto L_seg201_0000_000189;               /* jmp 0x0189 */
L_seg201_0000_00021B:;
L_seg201_0000_00021B:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg201_0230(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->ax = (uint16_t)(0x4EF);             /* mov ax, 0x4EF */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    push16(cpu, 0x1);                        /* push 0x1 */
    cpu->ax = (uint16_t)(0x1B6);             /* mov ax, 0x1B6 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->dx = (uint16_t)(0x11);              /* mov dx, 0x11 */
    cpu->cx = (uint16_t)(0x280);             /* mov cx, 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1C10(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0xA);               /* mov ax, 0xA */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1C6C(cpu);                        /* call 0000:0BB8 */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:0BF5 */ /* call 0000:0BF5 */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x2);               /* mov ax, 0x2 */
    /* unresolved far call call 0000:0264 */ /* call 0000:0264 */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x3);               /* mov ax, 0x3 */
    /* unresolved far call call 0000:0271 */ /* call 0000:0271 */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x4);               /* mov ax, 0x4 */
    /* unresolved far call call 0000:027E */ /* call 0000:027E */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    /* unresolved far call call 0000:028B */ /* call 0000:028B */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x6);               /* mov ax, 0x6 */
    /* unresolved far call call 0000:0298 */ /* call 0000:0298 */
    cpu->bx = (uint16_t)(0x234);             /* mov bx, 0x234 */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    cpu->ax = (uint16_t)(0x8);               /* mov ax, 0x8 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1CCA(cpu);                        /* call 0000:02A5 */
    cpu->ax = (uint16_t)(SEG_91);            /* mov ax, 0xFFFF  /* selector for seg91 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, 0x518), 0x0); /* cmp byte es:[0x518], 0x0 */
    if (cc_e(cpu)) goto L_seg201_0230_000334; /* je 0x0334 */
    cpu->ax = (uint16_t)(0xFD);              /* mov ax, 0xFD */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
L_seg201_0230_0002C8:;
L_seg201_0230_0002C8:;
    mem_write16(cpu, cpu->ds, 0x234, (uint16_t)(cpu->ax)); /* mov word ds:[0x234], ax */
    mem_write16(cpu, cpu->ds, 0x236, (uint16_t)(cpu->bx)); /* mov word ds:[0x236], bx */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x238) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x238, (uint16_t)(_r)); } /* and word ds:[0x238], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x23A) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x23A, (uint16_t)(_r)); } /* and word ds:[0x23A], 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0xC);               /* mov ax, 0xC */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x28);              /* mov ax, 0x28 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x1);                        /* push 0x1 */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_2B4E(cpu);                        /* call 0000:0C15 */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    push16(cpu, 0x1);                        /* push 0x1 */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->cx = mem_read16(cpu, cpu->es, 0x1E2); /* les cx, word es:[0x1E2] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x1E2 + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_3DFC(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x53)); /* lea ax, word ds:[si+0x53] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)(0x5);               /* mov cx, 0x5 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_12B2(cpu);                        /* call 0000:FFFF */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->ax = mem_read16(cpu, cpu->es, 0x1E6); /* les ax, word es:[0x1E6] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x1E6 + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE0), (uint16_t)(cpu->ax)); /* mov word ds:[si+0xE0], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE2), (uint16_t)(cpu->es)); /* mov word ds:[si+0xE2], es */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    goto L_seg201_0230_00033B;               /* jmp 0x033B */
L_seg201_0230_000334:;
L_seg201_0230_000334:;
    cpu->ax = (uint16_t)(0xBD);              /* mov ax, 0xBD */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    goto L_seg201_0230_0002C8;               /* jmp 0x02C8 */
L_seg201_0230_00033B:;
L_seg201_0230_00033B:;
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg201_0382(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x24)); /* sub sp, 0x24 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x2], cx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->bx);           /* mov si, bx */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    /* unresolved far call call 0000:0D0B */ /* call 0000:0D0B */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg201_0382_0003B4; /* jne 0x03B4 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg205_03F0(cpu);                        /* call 0000:FFFF */
    flags_cmp16(cpu, cpu->ax, 0x1B);         /* cmp ax, 0x1B */
    if (cc_e(cpu)) goto L_seg201_0382_0003AE; /* je 0x03AE */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg201_0382_0003B1;               /* jmp 0x03B1 */
L_seg201_0382_0003AE:;
L_seg201_0382_0003AE:;
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
L_seg201_0382_0003B1:;
L_seg201_0382_0003B1:;
    goto L_seg201_0382_0007DC;               /* jmp 0x07DC */
L_seg201_0382_0003B4:;
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_0000(cpu);                        /* call 0000:FFFF */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    /* unresolved far call call 0000:08F4 */ /* call 0000:08F4 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ax = (uint16_t)(SEG_99);            /* mov ax, 0x8FB  /* selector for seg99 */ */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x4], ds */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)mem_read16(cpu, cpu->ds, 0x2); cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul word ds:[0x2] */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->ax)); /* sub bx, ax */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x5)); /* add ax, 0x5 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    cpu->bx = (uint16_t)(0x1);               /* mov bx, 0x1 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg146_00E6(cpu);                        /* call 0000:FFFF */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x29);              /* mov ax, 0x29 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x6], dx */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x900);             /* mov ax, 0x900 */
    /* unresolved far call call 0000:03EF */ /* call 0000:03EF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    mem_write16(cpu, cpu->ds, cpu->bx, (uint16_t)(cpu->ax)); /* mov word ds:[bx], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2), (uint16_t)(cpu->dx)); /* mov word ds:[bx+0x2], dx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->cl = (uint8_t)(0xFF);               /* mov cl, 0xFF */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_0174(cpu);                        /* call 0000:FFFF */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x200);             /* mov ax, 0x200 */
    /* unresolved far call call 0000:03FF */ /* call 0000:03FF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xC], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0xA], dx */
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0xA02);             /* mov ax, 0xA02 */
    /* unresolved far call call 0000:0422 */ /* call 0000:0422 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x10], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0xE], dx */
    { uint8_t _r = cpu->bl ^ cpu->bl; flags_logic8(cpu, _r); cpu->bl = (uint8_t)(_r); } /* xor bl, bl */
    cpu->ax = (uint16_t)(0xA4);              /* mov ax, 0xA4 */
    /* unresolved far call call 0000:0432 */ /* call 0000:0432 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x14], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x12], dx */
    /* unresolved far call call 0000:040C */ /* call 0000:040C */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg229_8026(cpu);                        /* call 0000:FFFF */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->bx = (uint16_t)(0x8A8);             /* mov bx, 0x8A8 */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write8(cpu, cpu->ds, 0x22B, (uint8_t)(cpu->al)); /* mov byte ds:[0x22B], al */
    /* unresolved far call call 0000:044D */ /* call 0000:044D */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_00BC(cpu);                        /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x18], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x16], dx */
    /* unresolved far call call 0000:0466 */ /* call 0000:0466 */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* les ax, word ss:[bp+-0x18] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_0984(cpu);                        /* call 0000:FFFF */
    mem_write16(cpu, cpu->ds, 0x230, (uint16_t)(cpu->ax)); /* mov word ds:[0x230], ax */
    mem_write16(cpu, cpu->ds, 0x232, (uint16_t)(cpu->dx)); /* mov word ds:[0x232], dx */
    /* unresolved far call call 0000:047C */ /* call 0000:047C */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x100);                      /* push 0x100 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* lds bx, word ss:[bp+-0x18] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* lds si, word ss:[bp+-0x18] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->si + 0x3DC)); /* lea cx, word ds:[si+0x3DC] */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    /* unresolved far call call 0000:0492 */ /* call 0000:0492 */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* les cx, word ss:[bp+-0x10] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    push16(cpu, 0x8);                        /* push 0x8 */
    push16(cpu, 0xA02);                      /* push 0xA02 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* lds bx, word ss:[bp+-0x18] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    /* unresolved far call call 0000:04AD */ /* call 0000:04AD */
    /* unresolved far call call 0000:04B2 */ /* call 0000:04B2 */
    push16(cpu, 0x2);                        /* push 0x2 */
    push16(cpu, 0xA4);                       /* push 0xA4 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* lds bx, word ss:[bp+-0x18] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14)); /* lds cx, word ss:[bp+-0x14] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x14) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    /* unresolved far call call 0000:04C9 */ /* call 0000:04C9 */
    /* unresolved far call call 0000:04CE */ /* call 0000:04CE */
    cpu->ax = (uint16_t)(0x45E);             /* mov ax, 0x45E */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x1A], ds */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14)); /* les ax, word ss:[bp+-0x14] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x14) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, 0x3);                        /* push 0x3 */
    push16(cpu, 0xA4);                       /* push 0xA4 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* les bx, word ss:[bp+-0x18] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14)); /* les cx, word ss:[bp+-0x14] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x14) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg189_07B6(cpu);                        /* call 0000:04E5 */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
    /* unresolved far call call 0000:04EA */ /* call 0000:04EA */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14)); /* les ax, word ss:[bp+-0x14] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x14) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg229_8252(cpu);                        /* call 0000:04FC */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* les bx, word ss:[bp+-0x18] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x3DC)); /* lea ax, word ds:[bx+0x3DC] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg221_00B0(cpu);                        /* call 0000:FFFF */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_01D2(cpu);                        /* call 0000:03BC */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_09E6(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_0658(cpu);                        /* call 0000:FFFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg204_0000(cpu);                        /* call 0000:0AEE */
    /* unresolved far call call 0000:0A3D */ /* call 0000:0A3D */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, 0x22B)); /* mov al, byte ds:[0x22B] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg229_0000(cpu);                        /* call 0000:0459 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg229_8580(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x14)); /* lea ax, word ss:[bp+-0x14] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    /* unresolved far call call 0000:0562 */ /* call 0000:0562 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_02F8(cpu);                        /* call 0000:03C1 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov ds, word ss:[bp+-0x4] */
    { int32_t _r = (int32_t)(int16_t)cpu->ax * (int16_t)mem_read16(cpu, cpu->ds, 0x2); cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)((uint32_t)_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | ((uint32_t)_r != (uint32_t)(int32_t)(int16_t)_r ? FLAG_CF|FLAG_OF : 0); } /* imul word ds:[0x2] */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->ax)); /* sub bx, ax */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x5)); /* add ax, 0x5 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    cpu->bx = (uint16_t)(0x1);               /* mov bx, 0x1 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg146_00E6(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x1C], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x1E], si */
    goto L_seg201_0382_000661;               /* jmp 0x0661 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x24), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x24], ax */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x13))); /* push word ds:[bx+si+0x13] */
    push16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x11))); /* push word ds:[bx+si+0x11] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x24)); /* lea ax, word ss:[bp+-0x24] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* lds bx, word ss:[bp+-0x18] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x40)); /* lea ax, word ds:[bx+0x40] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)); /* lds bx, word ss:[bp+-0xC] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xC) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di), (uint16_t)(cpu->ax)); /* mov word ds:[bx+di], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2), (uint16_t)(cpu->dx)); /* mov word ds:[bx+di+0x2], dx */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)); /* lds bx, word ss:[bp+-0xC] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xC) + 2));
    cpu->di = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di)); /* lds di, word ds:[bx+di] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->di) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x20], ds */
    goto L_seg201_0382_000698;               /* jmp 0x0698 */
L_seg201_0382_0005EA:;
L_seg201_0382_0005EA:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x6))); /* mov ax, word ds:[bx+si+0x6] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->dx = (uint16_t)(cpu->ax);           /* mov dx, ax */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds ax, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* les bx, word ss:[bp+-0x10] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x6))); /* push word es:[bx+si+0x6] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x8))); /* push word es:[bx+si+0x8] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0xA))); /* push word es:[bx+si+0xA] */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x2))); /* mov cx, word es:[bx+si+0x2] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x4))); /* mov bx, word es:[bx+si+0x4] */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->dx)); /* sub bx, dx */
    cpu->dx = (uint16_t)(cpu->bx);           /* mov dx, bx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_01B0(cpu);                        /* call 0000:FFFF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x6))); /* mov ax, word ds:[bx+si+0x6] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg221_004E(cpu);                        /* call 0000:05F1 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15))); /* mov al, byte ds:[bx+si+0x15] */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20))); /* push word ss:[bp+-0x20] */
    push16(cpu, cpu->di);                    /* push di */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x2))); /* mov ax, word ds:[bx+si+0x2] */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x4))); /* mov di, word ds:[bx+si+0x4] */
    cpu->di = (uint16_t)(flags_sub16(cpu, cpu->di, cpu->cx)); /* sub di, cx */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x6))); /* mov dx, word ds:[bx+si+0x6] */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E))); /* mov si, word ss:[bp+-0x1E] */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_0526(cpu);                        /* call 0000:FFFF */
    /* unresolved far call call 0000:051A */ /* call 0000:051A */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x1E], si */
L_seg201_0382_00065A:;
L_seg201_0382_00065A:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C))); /* mov ax, word ss:[bp+-0x1C] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x1C], ax */
L_seg201_0382_000661:;
L_seg201_0382_000661:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), cpu->ax); /* cmp word ds:[bx], ax */
    if (cc_le(cpu)) goto L_seg201_0382_0006A1; /* jle 0x06A1 */
    cpu->si = (uint16_t)(0x14);              /* mov si, 0x14 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->si; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul si */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xE))); /* mov al, byte ds:[bx+si+0xE] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    { uint16_t _r = cpu->ax & 0xF; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* and ax, 0xF */
    flags_cmp16(cpu, cpu->ax, 0x1);          /* cmp ax, 0x1 */
    if (cc_ne(cpu)) goto L_seg201_0382_00065A; /* jne 0x065A */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xF))); /* mov al, byte ds:[bx+si+0xF] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    flags_logic8(cpu, cpu->cl & 0x40);       /* test cl, 0x40 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si)) & cpu->ah); /* test byte ss:[bp+si], ah */
    { int _cf = cf(cpu); cpu->bp = (uint16_t)(flags_add16(cpu, cpu->bp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc bp */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->halted = 1; return;                 /* hlt */
    cpu->di = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di)); /* lds di, word ds:[bx+di] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->di) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x20], ds */
L_seg201_0382_000698:;
L_seg201_0382_000698:;
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->di; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, di */
    if (cc_e(cpu)) goto L_seg201_0382_00065A; /* je 0x065A */
    goto L_seg201_0382_0005EA;               /* jmp 0x05EA */
L_seg201_0382_0006A1:;
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg146_01F4(cpu);                        /* call 0000:053E */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg146_0000(cpu);                        /* call 0000:0652 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:0555 */ /* call 0000:0555 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:06AF */ /* call 0000:06AF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_0A5A(cpu);                        /* call 0000:054D */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10)); /* lds bx, word ss:[bp+-0x10] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x10) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec ax */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
L_seg201_0382_0006C8:;
L_seg201_0382_0006C8:;
    flags_logic16(cpu, cpu->cx & cpu->cx);   /* test cx, cx */
    if (cc_l(cpu)) goto L_seg201_0382_0006E1; /* jl 0x06E1 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)); /* lds bx, word ss:[bp+-0xC] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xC) + 2));
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->si)); /* lea ax, word ds:[bx+si] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:0579 */ /* call 0000:0579 */
    { int _cf = cf(cpu); cpu->cx = (uint16_t)(flags_sub16(cpu, cpu->cx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec cx */
    goto L_seg201_0382_0006C8;               /* jmp 0x06C8 */
L_seg201_0382_0006E1:;
L_seg201_0382_0006E1:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x10)); /* lea ax, word ss:[bp+-0x10] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:06DA */ /* call 0000:06DA */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0202(cpu);                        /* call 0000:057E */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18)); /* les cx, word ss:[bp+-0x18] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x18) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0000(cpu);                        /* call 0x0000 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x18)); /* lea ax, word ss:[bp+-0x18] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_0216(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:06B7 */ /* call 0000:06B7 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_0000(cpu);                        /* call 0000:FFFF */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A))); /* mov ds, word ss:[bp+-0x1A] */
    cpu->ax = mem_read16(cpu, cpu->ds, 0x22C); /* lds ax, word ds:[0x22C] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x22C + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* les cx, word ss:[bp+-0x8] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg222_1B7C(cpu);                        /* call 0000:FFFF */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* push word ss:[bp+-0x2] */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A))); /* mov ds, word ss:[bp+-0x1A] */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x22E)); /* push word ds:[0x22E] */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x22C)); /* push word ds:[0x22C] */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x232)); /* push word ds:[0x232] */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x230)); /* push word ds:[0x230] */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* les ax, word ss:[bp+-0x8] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->cx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6)); /* lds cx, word ss:[bp+0x6] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp + 0x6) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg149_0124(cpu);                        /* call 0000:FFFF */
    cpu->cl = (uint8_t)(cpu->al);            /* mov cl, al */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg221_0076(cpu);                        /* call 0000:06EE */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_0AB8(cpu);                        /* call 0000:0713 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_037C(cpu);                        /* call 0000:FFFF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x4))); /* mov ax, word ds:[bx+0x4] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg222_08E6(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg222_16BC(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_0030(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_07D4(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg183_028A(cpu);                        /* call 0000:FFFF */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0220(cpu);                        /* call 0x0220 */
    cpu->ax = (uint16_t)(0x230);             /* mov ax, 0x230 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A))); /* mov bx, word ss:[bp+-0x1A] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg211_03EE(cpu);                        /* call 0000:FFFF */
    cpu->ax = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds ax, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg203_01A2(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0xC)); /* lea ax, word ss:[bp+-0xC] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:06E7 */ /* call 0000:06E7 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->ax = (uint16_t)(cpu->bx);           /* lea ax, word ds:[bx] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:07B2 */ /* call 0000:07B2 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x8)); /* lea ax, word ss:[bp+-0x8] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:07BE */ /* call 0000:07BE */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->cx); cpu->cx = (uint16_t)(_t); } /* xchg ax, cx */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    flags_cmp16(cpu, cpu->ax, 0xFFFF);       /* cmp ax, 0xFFFF */
    if (cc_e(cpu)) goto L_seg201_0382_0007D9; /* je 0x07D9 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg201_0382_0007DC;               /* jmp 0x07DC */
L_seg201_0382_0007D9:;
L_seg201_0382_0007D9:;
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
L_seg201_0382_0007DC:;
L_seg201_0382_0007DC:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0x8; return;                  /* retf 0x4 */
}

void seg201_07E4(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0xA)); /* sub sp, 0xA */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1), (uint8_t)(cpu->cl)); /* mov byte ss:[bp+-0x1], cl */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->bx);           /* mov si, bx */
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* unresolved far call call 0000:0B01 */ /* call 0000:0B01 */
    flags_logic8(cpu, cpu->cl & cpu->cl);    /* test cl, cl */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic16(cpu, cpu->dx & cpu->sp);   /* test dx, sp */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si - 0x1), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si - 0x1)), cpu->bh))); /* add byte ds:[bx+si+-0x1], bh */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cl = (uint8_t)(0xFF);               /* mov cl, 0xFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_115E(cpu);                        /* call 0000:0AC6 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x7500)) & cpu->bp); /* test word ss:[bp+di+-0x7500], bp */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x6522), (uint16_t)(0xE2E)); /* mov word ss:[bp+di+-0x6522], 0xE2E */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si)), cpu->al))); /* add byte ds:[bx+si], al */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x1EA);             /* mov ax, 0x1EA */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg214_122E(cpu);                        /* call 0000:0016 */
L_seg201_07E4_00082E:;
L_seg201_07E4_00082E:;
    cpu->ax = (uint16_t)(0x9C5);             /* mov ax, 0x9C5 */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0x4)); /* mov ax, word ds:[0x4] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0xA)); /* add ax, 0xA */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0230(cpu);                        /* call 0000:09D1 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_00E4(cpu);                        /* call 0000:09D6 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg132_008C(cpu);                        /* call 0000:FFFF */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1)), 0x0); /* cmp byte ss:[bp+-0x1], 0x0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, cpu->bl & cpu->cl);    /* test bl, cl */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x89A), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x89A)), cpu->al))); /* add byte ss:[bp+di+-0x89A], al */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x69A), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x69A)), cpu->al))); /* add byte ss:[bp+di+-0x69A], al */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x4), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x4)), cpu->bh))); /* add byte ds:[bx+si+0x4], bh */
    /* unresolved far call call 0000:0A92 */ /* call 0000:0A92 */
    cpu->dx = (uint16_t)(cpu->ax);           /* mov dx, ax */
    cpu->ax = (uint16_t)(SEG_16);            /* mov ax, 0x989  /* selector for seg16 */ */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    mem_write8(cpu, cpu->ds, 0x1, (uint8_t)(0xFF)); /* mov byte ds:[0x1], 0xFF */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x7))); /* push word ss:[bp+-0x7] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x9))); /* push word ss:[bp+-0x9] */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0382(cpu);                        /* call 0x0382 */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg196_0510(cpu);                        /* call 0000:085C */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x9)); /* lea ax, word ss:[bp+-0x9] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_2C20(cpu);                        /* call 0000:0A9C */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg215_0390(cpu);                        /* call 0000:0AA1 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:0ACD */ /* call 0000:0ACD */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_01D2(cpu);                        /* call 0000:FFFF */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1)), 0x0); /* cmp byte ss:[bp+-0x1], 0x0 */
    if (cc_ne(cpu)) goto L_seg201_07E4_0008B4; /* jne 0x08B4 */
    cpu->bx = (uint16_t)(0xFFFF);            /* mov bx, 0xFFFF */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_115E(cpu);                        /* call 0000:FFFF */
L_seg201_07E4_0008B4:;
L_seg201_07E4_0008B4:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_0184(cpu);                        /* call 0000:0896 */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:07F8 */ /* call 0000:07F8 */
    goto L_seg201_07E4_000932;               /* jmp 0x0932 */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg221_0076(cpu);                        /* call 0000:08BE */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg205_0FE4(cpu);                        /* call 0000:09AB */
    cpu->ax = (uint16_t)(0x4E);              /* mov ax, 0x4E */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg137_0072(cpu);                        /* call 0000:09B3 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x280);                      /* push 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_08AA(cpu);                        /* call 0000:0010 */
    goto L_seg201_07E4_000932;               /* jmp 0x0932 */
    cpu->ax = (uint16_t)(0x82F);             /* mov ax, 0x82F */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = mem_read16(cpu, cpu->ds, 0x651); /* lds ax, word ds:[0x651] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x651 + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x5), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x5], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x3), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x3], ds */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(0x8E5);             /* mov ax, 0x8E5 */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(SEG_24);            /* mov ax, 0xFFFF  /* selector for seg24 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, 0x16)); /* mov al, byte es:[0x16] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0x4)); /* mov ax, word ds:[0x4] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0xA)); /* add ax, 0xA */
    cpu->dx = (uint16_t)(cpu->ax);           /* mov dx, ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    /* UNHANDLED: call far word ss:[bp+-0x5] */ /* call far word ss:[bp+-0x5] */
    goto L_seg201_07E4_00082E;               /* jmp 0x082E */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0230(cpu);                        /* call 0x0230 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x9), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x9], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x7), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x7], dx */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x9)); /* lds bx, word ss:[bp+-0x9] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x9) + 2));
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x7A)); /* lds bx, word ds:[bx+0x7A] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0x7A) + 2));
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x8)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x8), (uint16_t)(_r)); } /* and word ds:[bx+0x8], 0x0 */
    /* jmp out of function to 0x000858 */    /* jmp 0x0858 */
L_seg201_07E4_000932:;
L_seg201_07E4_000932:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg201_0938(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x16)); /* sub sp, 0x16 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ax, word ss:[bp+-0x2] */
    { uint16_t _r = cpu->ax | mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, word ss:[bp+-0x4] */
    if (cc_e(cpu)) goto L_seg201_0938_0009C1; /* je 0x09C1 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), 0x0); /* cmp word ds:[bx], 0x0 */
    if (cc_ne(cpu)) goto L_seg201_0938_000972; /* jne 0x0972 */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea cx, word ss:[bp+-0x4] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    /* unresolved far call call 0000:0948 */ /* call 0000:0948 */
    goto L_seg201_0938_0009C1;               /* jmp 0x09C1 */
L_seg201_0938_000972:;
L_seg201_0938_000972:;
    { uint8_t _r = cpu->al ^ cpu->al; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* xor al, al */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(SEG_74);            /* mov ax, 0xB16  /* selector for seg74 */ */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x6], ds */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, 0x243), 0x0); /* cmp byte ds:[0x243], 0x0 */
    if (cc_ne(cpu)) goto L_seg201_0938_0009C4; /* jne 0x09C4 */
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write8(cpu, cpu->es, 0x1, (uint8_t)(0xFF)); /* mov byte es:[0x1], 0xFF */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cl = (uint8_t)(0xFF);               /* mov cl, 0xFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_115E(cpu);                        /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg201_0938_0009C4; /* je 0x09C4 */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:0975 */ /* call 0000:0975 */
    /* unresolved far call call 0000:0CD4 */ /* call 0000:0CD4 */
    cpu->ax = (uint16_t)(0x4E);              /* mov ax, 0x4E */
    /* unresolved far call call 0000:0E14 */ /* call 0000:0E14 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x280);                      /* push 0x280 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_08AA(cpu);                        /* call 0000:0010 */
L_seg201_0938_0009C1:;
L_seg201_0938_0009C1:;
    goto L_seg201_0938_000B05;               /* jmp 0x0B05 */
L_seg201_0938_0009C4:;
L_seg201_0938_0009C4:;
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, 0x4)); /* mov ax, word es:[0x4] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0xA)); /* add ax, 0xA */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg132_008C(cpu);                        /* call 0000:FFFF */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, 0x242), 0x0); /* cmp byte ds:[0x242], 0x0 */
    if (cc_e(cpu)) goto L_seg201_0938_000A10; /* je 0x0A10 */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(_r)); } /* and word ss:[bp+-0xA], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(_r)); } /* and word ss:[bp+-0x8], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(_r)); } /* and word ss:[bp+-0xE], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(_r)); } /* and word ss:[bp+-0xC], 0x0 */
L_seg201_0938_0009F6:;
L_seg201_0938_0009F6:;
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x10], ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(0x1)); /* mov word ss:[bp+-0x12], 0x1 */
    cpu->di = (uint16_t)(SEG_85);            /* mov di, 0xFFFF  /* selector for seg85 */ */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x14], di */
    goto L_seg201_0938_000A2F;               /* jmp 0x0A2F */
L_seg201_0938_000A10:;
L_seg201_0938_000A10:;
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0230(cpu);                        /* call 0x0230 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x8], dx */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA)); /* lds bx, word ss:[bp+-0xA] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xA) + 2));
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x7A)); /* lds bx, word ds:[bx+0x7A] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0x7A) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x8), (uint16_t)(0x1)); /* mov word ds:[bx+0x8], 0x1 */
    goto L_seg201_0938_0009F6;               /* jmp 0x09F6 */
L_seg201_0938_000A28:;
L_seg201_0938_000A28:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16))); /* mov bx, word ss:[bp+-0x16] */
    { int _cf = cf(cpu); cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc bx */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ss:[bp+-0x12] */
L_seg201_0938_000A2F:;
L_seg201_0938_000A2F:;
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les si, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)mem_read16(cpu, cpu->es, cpu->si); cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv word es:[si] */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->dx); cpu->dx = (uint16_t)(_t); } /* xchg ax, dx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x16], bx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->si = (uint16_t)(0xF);               /* mov si, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->bx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul bx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->bx = (uint16_t)(0x1ED);             /* mov bx, 0x1ED */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(0x1FA);             /* mov ax, 0x1FA */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)(0x3E2);             /* mov ax, 0x3E2 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x84)); /* lea cx, word ds:[bx+si+0x84] */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg173_0572(cpu);                        /* call 0000:FFFF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), 0x1); /* cmp word ds:[bx], 0x1 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x3300)) & cpu->ax); /* test word ds:[bx+si+0x3300], ax */
    /* TODO: ror mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x38)), 0x76 */ /* ror byte ss:[bp+di+-0x38], 0x76 */
    cpu->flags &= ~FLAG_CF;                  /* clc */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* push word ss:[bp+-0xA] */
    cpu->ax = (uint16_t)(0x3E2);             /* mov ax, 0x3E2 */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov di, word ss:[bp+-0x14] */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0382(cpu);                        /* call 0x0382 */
    flags_logic8(cpu, cpu->al & cpu->al);    /* test al, al */
    if (cc_e(cpu)) goto L_seg201_0938_000A28; /* je 0x0A28 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    /* unresolved far call call 0000:09FA */ /* call 0000:09FA */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0xA)); /* lea ax, word ss:[bp+-0xA] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:0D75 */ /* call 0000:0D75 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_01D2(cpu);                        /* call 0000:FFFF */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ds, word ss:[bp+-0x6] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, 0x243), 0x0); /* cmp byte ds:[0x243], 0x0 */
    if (cc_ne(cpu)) goto L_seg201_0938_000ACA; /* jne 0x0ACA */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg201_0938_000ACA:;
L_seg201_0938_000ACA:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    /* unresolved far call call 0000:0AA9 */ /* call 0000:0AA9 */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea cx, word ss:[bp+-0x4] */
    cpu->dx = (uint16_t)(cpu->ss);           /* mov dx, ss */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    { uint16_t _r = cpu->bx ^ cpu->bx; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* xor bx, bx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg221_1156(cpu);                        /* call 0000:096C */
    mem_write8(cpu, cpu->ds, 0x242, (uint8_t)(0x0)); /* mov byte ds:[0x242], 0x0 */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, 0x243), 0x0); /* cmp byte ds:[0x243], 0x0 */
    if (cc_e(cpu)) goto L_seg201_0938_000AFE; /* je 0x0AFE */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    goto L_seg201_0938_000B05;               /* jmp 0x0B05 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x91))); /* mov ax, word ds:[bx+si+0x91] */
    /* jmp out of function to 0x000A76 */    /* jmp 0x0A76 */
L_seg201_0938_000AFE:;
L_seg201_0938_000AFE:;
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:09A6 */ /* call 0000:09A6 */
L_seg201_0938_000B05:;
L_seg201_0938_000B05:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg201_0B0C(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x46)); /* sub sp, 0x46 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->bx = (uint16_t)(0xB9A);             /* mov bx, 0xB9A */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write8(cpu, cpu->es, 0x242, (uint8_t)(cpu->al)); /* mov byte es:[0x242], al */
    mem_write8(cpu, cpu->es, 0x243, (uint8_t)(cpu->al)); /* mov byte es:[0x243], al */
    cpu->bx = (uint16_t)(SEG_94);            /* mov bx, 0xFFFF  /* selector for seg94 */ */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg135_0070(cpu);                        /* call 0000:FFFF */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea ax, word ss:[bp+-0x46] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:0E3B */ /* call 0000:0E3B */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x46)); /* lea ax, word ss:[bp+-0x46] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg201_0938(cpu);                        /* call 0x0938 */
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

