/* Segment 221 - 9408 bytes, 8 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "segments.h"

void seg221_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x4)); /* lea ax, word ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg209_109E(cpu);                        /* call 0000:FFFF */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov al, byte ss:[bp+-0x4] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->ax = (uint16_t)(0x1A0B);            /* mov ax, 0x1A0B */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->bx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul bx */
    cpu->bl = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x3))); /* mov bl, byte ss:[bp+-0x3] */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->si = (uint16_t)(0x1770);            /* mov si, 0x1770 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->bx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul bx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, cpu->si)); /* add cx, si */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov al, byte ss:[bp+-0x2] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->ax = (uint16_t)(0x64);              /* mov ax, 0x64 */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->bx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul bx */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, cpu->ax)); /* add cx, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1))); /* mov al, byte ss:[bp+-0x1] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, cpu->ax)); /* add cx, ax */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    cpu->bx = (uint16_t)(pop16(cpu));        /* pop bx */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_0144(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x74)); /* sub sp, 0x74 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(_r)); } /* and word ss:[bp+-0x8], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(_r)); } /* and word ss:[bp+-0x6], 0x0 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD2))); /* mov ax, word ds:[si+0xD2] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE0)); /* les bx, word ds:[si+0xE0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xE0) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0xC], es */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xE], bx */
    flags_cmp16(cpu, mem_read16(cpu, cpu->es, cpu->bx), cpu->ax); /* cmp word es:[bx], ax */
    if (cc_g(cpu)) goto L_seg221_0144_00017B; /* jg 0x017B */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg221_0144_0001DF;               /* jmp 0x01DF */
L_seg221_0144_00017B:;
L_seg221_0144_00017B:;
    cpu->si = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB0)); /* lds si, word ds:[si+0xB0] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB0) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x10], ds */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x12], si */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x12))); /* mov cx, word ds:[si+0x12] */
    { int _cf = cf(cpu); cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x14], cx */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x10))); /* mov di, word ds:[si+0x10] */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x16], di */
    cpu->cx = (uint16_t)(SEG_98);            /* mov cx, 0x4D2  /* selector for seg98 */ */
    cpu->ds = (uint16_t)(cpu->cx);           /* mov ds, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x18], ds */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    { uint16_t _v = cpu->si; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, cl */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x2)); /* lea cx, word ds:[bx+si+0x2] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, 0x8C0), 0x0); /* cmp byte ds:[0x8C0], 0x0 */
    if (cc_e(cpu)) goto L_seg221_0144_0001E2; /* je 0x01E2 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x8);               /* mov ax, 0x8 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x5E)); /* lea ax, word ss:[bp+-0x5E] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:0DA3 */ /* call 0000:0DA3 */
L_seg221_0144_0001C3:;
L_seg221_0144_0001C3:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x5E)); /* lea ax, word ss:[bp+-0x5E] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_00BC(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x62], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x60), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x60], bx */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    { uint16_t _r = cpu->cx | cpu->ax; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* or cx, ax */
    if (cc_ne(cpu)) goto L_seg221_0144_0001FA; /* jne 0x01FA */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg221_0144_0001DF:;
L_seg221_0144_0001DF:;
    goto L_seg221_0144_000486;               /* jmp 0x0486 */
L_seg221_0144_0001E2:;
L_seg221_0144_0001E2:;
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x12);              /* mov ax, 0x12 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x1B);              /* mov ax, 0x1B */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x5E)); /* lea ax, word ss:[bp+-0x5E] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg173_0572(cpu);                        /* call 0000:01BF */
    goto L_seg221_0144_0001C3;               /* jmp 0x01C3 */
L_seg221_0144_0001FA:;
L_seg221_0144_0001FA:;
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x6);                        /* push 0x6 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_0680(cpu);                        /* call 0000:0DCF */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62)); /* lds bx, word ss:[bp+-0x62] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x62) + 2));
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x66), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x66], bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x64), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x64], ds */
    cpu->ax = (uint16_t)(0x505);             /* mov ax, 0x505 */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x68), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x68], es */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->bx; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, bx */
    if (cc_e(cpu)) goto L_seg221_0144_00025E; /* je 0x025E */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, 0)); /* mov ax, word es:[0x0] */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_sub16(cpu, cpu->cx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xA)))); /* sub cx, word ds:[bx+0xA] */
    cpu->ax = (uint16_t)(0x2);               /* mov ax, 0x2 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->cx); cpu->cx = (uint16_t)(_t); } /* xchg ax, cx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->cx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->cx); cpu->cx = (uint16_t)(_t); } /* xchg ax, cx */
    { int _cf = cf(cpu); cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc cx */
    cpu->di = (uint16_t)(flags_sub16(cpu, cpu->di, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xC)))); /* sub di, word ds:[bx+0xC] */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 0xFFF8)); /* add di, 0xFFF8 */
    cpu->ax = (uint16_t)(0x2);               /* mov ax, 0x2 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->di; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv di */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->di);                    /* push di */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov ax, word ss:[bp+-0x12] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov bx, word ss:[bp+-0x10] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_389C(cpu);                        /* call 0000:0E19 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x66)); /* lea ax, word ss:[bp+-0x66] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_2C84(cpu);                        /* call 0000:0E23 */
L_seg221_0144_00025E:;
L_seg221_0144_00025E:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62)); /* lds bx, word ss:[bp+-0x62] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x62) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x13B))); /* mov ax, word ds:[bx+0x13B] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x13D))); /* mov ax, word ds:[bx+0x13D] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6], ax */
    cpu->ax = (uint16_t)(SEG_92);            /* mov ax, 0x4C4  /* selector for seg92 */ */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0x56E)); /* mov ax, word ds:[0x56E] */
    /* unresolved far call call 0000:04E4 */ /* call 0000:04E4 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6A), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6A], ax */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:0FB6 */ /* call 0000:0FB6 */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6C), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6C], ax */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds si, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x1))); /* mov al, byte es:[bx+0x1] */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6D), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x6D], al */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x3))); /* mov al, byte es:[bx+0x3] */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6E), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x6E], al */
    cpu->ax = (uint16_t)(SEG_24);            /* mov ax, 0x215  /* selector for seg24 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, 0x16)); /* mov al, byte es:[0x16] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    if (cc_ne(cpu)) goto L_seg221_0144_0002B9; /* jne 0x02B9 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    goto L_seg221_0144_0002BE;               /* jmp 0x02BE */
L_seg221_0144_0002B9:;
L_seg221_0144_0002B9:;
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 0x3)); /* add cx, 0x3 */
L_seg221_0144_0002BE:;
L_seg221_0144_0002BE:;
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x3), (uint8_t)(cpu->cl)); /* mov byte es:[bx+0x3], cl */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di - 0x75FF)) & cpu->ch); /* test byte ds:[bx+di+-0x75FF], ch */
    cpu->st[0] = fpu_read_f32(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si)) - cpu->st[0]; /* fsubr dword word ss:[bp+si] word ss:[bp+si] */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si - 0x6EA2), (uint16_t)(flags_sub16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si - 0x6EA2)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec word ds:[bx+si+-0x6EA2] */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x4001)) & cpu->ah); /* test byte ds:[bx+di+0x4001], ah */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
L_seg221_0144_0002E1:;
L_seg221_0144_0002E1:;
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x70), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x70], al */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x72), (uint16_t)(0x6)); /* mov word ss:[bp+-0x72], 0x6 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x68))); /* mov ds, word ss:[bp+-0x68] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->dx = (uint16_t)(0x2);               /* mov dx, 0x2 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov ax, word ss:[bp+-0x12] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov bx, word ss:[bp+-0x10] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_4388(cpu);                        /* call 0000:0EAE */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->bx = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xB4)); /* les bx, word es:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6F))); /* mov al, byte ss:[bp+-0x6F] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[bx+0x1], al */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov si, word ss:[bp+-0xA] */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    cpu->di = (uint16_t)(cpu->si);           /* mov di, si */
    { uint16_t _v = cpu->di; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, cl */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov bx, word ss:[bp+-0xE] */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x2)); /* lea ax, word ds:[bx+di+0x2] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov dx, word ss:[bp+-0xC] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->cx = (uint16_t)(0xEC8);             /* mov cx, 0xEC8 */
    cpu->es = (uint16_t)(cpu->cx);           /* mov es, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x74), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x74], es */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->si; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, cl */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x2)); /* lea bx, word ds:[bx+si+0x2] */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16))); /* mov ax, word ss:[bp+-0x16] */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, mem_read16(cpu, cpu->es, 0x4))); /* sub ax, word es:[0x4] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov dx, word ss:[bp+-0x12] */
    push16(cpu, cpu->dx);                    /* push dx */
    /* unresolved far call call 0000:0F92 */ /* call 0000:0F92 */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x10)); /* add sp, 0x10 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov bx, word ds:[0x0] */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les bx, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0xB4)); /* les bx, word es:[bx+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->bx + 0xB4) + 2));
    cpu->cl = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6F))); /* mov cl, byte ss:[bp+-0x6F] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x1), (uint8_t)(cpu->cl)); /* mov byte es:[bx+0x1], cl */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov di, word ds:[0x0] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov si, word ss:[bp+-0xA] */
    cpu->cl = (uint8_t)(0x5);                /* mov cl, 0x5 */
    { uint16_t _v = cpu->si; uint8_t _c = cpu->cl; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, cl */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE)); /* les bx, word ss:[bp+-0xE] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0xE) + 2));
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0xF))); /* push word es:[bx+si+0xF] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18))); /* push word ss:[bp+-0x18] */
    cpu->bx = (uint16_t)(0x25);              /* mov bx, 0x25 */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov bx, word ss:[bp+-0x14] */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->di)); /* sub bx, di */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x72))); /* mov bx, word ss:[bp+-0x72] */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->dx);                    /* push dx */
    /* unresolved far call call 0000:0350 */ /* call 0000:0350 */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x12)); /* add sp, 0x12 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x74))); /* mov es, word ss:[bp+-0x74] */
    cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, mem_read16(cpu, cpu->es, 0x4))); /* add bx, word es:[0x4] */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les si, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->si = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xB4)); /* les si, word es:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x70))); /* mov al, byte ss:[bp+-0x70] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->si + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[si+0x1], al */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62)); /* les si, word ss:[bp+-0x62] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x62) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x2BD))); /* push word es:[si+0x2BD] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x2BB))); /* push word es:[si+0x2BB] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x2B9))); /* push word es:[si+0x2B9] */
    push16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x2B7))); /* push word es:[si+0x2B7] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18))); /* mov cx, word ss:[bp+-0x18] */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(0x29);              /* mov si, 0x29 */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov di, word ss:[bp+-0x14] */
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    cpu->si = (uint16_t)(flags_sub16(cpu, cpu->si, cpu->ax)); /* sub si, ax */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov si, word ss:[bp+-0x10] */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    /* unresolved far call call 0000:0393 */ /* call 0000:0393 */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x18)); /* add sp, 0x18 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x74))); /* mov es, word ss:[bp+-0x74] */
    cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, mem_read16(cpu, cpu->es, 0x4))); /* add bx, word es:[0x4] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* push word ss:[bp+-0x6] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* push word ss:[bp+-0x8] */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->cx = (uint16_t)(0x31);              /* mov cx, 0x31 */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->di = (uint16_t)(flags_sub16(cpu, cpu->di, cpu->ax)); /* sub di, ax */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->si);                    /* push si */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov di, word ss:[bp+-0x12] */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_466E(cpu);                        /* call 0000:03E8 */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x14)); /* add sp, 0x14 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->si = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xB4)); /* les si, word ds:[bx+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6E))); /* mov al, byte ss:[bp+-0x6E] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->si + 0x3), (uint8_t)(cpu->al)); /* mov byte es:[si+0x3], al */
    cpu->si = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xB4)); /* les si, word ds:[bx+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6D))); /* mov al, byte ss:[bp+-0x6D] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->si + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[si+0x1], al */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6C))); /* mov ax, word ss:[bp+-0x6C] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_43A8(cpu);                        /* call 0000:0282 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6A))); /* mov ax, word ss:[bp+-0x6A] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg204_087C(cpu);                        /* call 0000:0278 */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov es, word ss:[bp+-0x10] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->di + 0x12))); /* mov ax, word es:[di+0x12] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->di + 0x10))); /* mov ax, word es:[di+0x10] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xB4)); /* lds bx, word ds:[bx+0xB4] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x3))); /* mov al, byte ds:[bx+0x3] */
    push16(cpu, cpu->ax);                    /* push ax */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg226_4138(cpu);                        /* call 0000:0FE2 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x62)); /* lea ax, word ss:[bp+-0x62] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_0216(cpu);                        /* call 0000:0FEC */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    goto L_seg221_0144_000486;               /* jmp 0x0486 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, 0xF)); /* add bx, 0xF */
    /* jmp out of function to 0x0002D3 */    /* jmp 0x02D3 */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x3)); /* add ax, 0x3 */
    goto L_seg221_0144_0002E1;               /* jmp 0x02E1 */
L_seg221_0144_000486:;
L_seg221_0144_000486:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_04F0(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8)); /* sub sp, 0x8 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->cx = (uint16_t)(0xE5C);             /* mov cx, 0xE5C */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x6], cx */
    cpu->cx = (uint16_t)(0x4FF);             /* mov cx, 0x4FF */
    cpu->ds = (uint16_t)(cpu->cx);           /* mov ds, cx */
    cpu->cx = (uint16_t)(0x5B9);             /* mov cx, 0x5B9 */
    cpu->es = (uint16_t)(cpu->cx);           /* mov es, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x8], es */
    push16(cpu, mem_read16(cpu, cpu->ds, 0x2)); /* push word ds:[0x2] */
    push16(cpu, 0x4);                        /* push 0x4 */
    push16(cpu, mem_read16(cpu, cpu->es, 0x49)); /* push word es:[0x49] */
    push16(cpu, mem_read16(cpu, cpu->es, 0x47)); /* push word es:[0x47] */
    push16(cpu, 0x1);                        /* push 0x1 */
    push16(cpu, 0x21C1);                     /* push 0x21C1 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ds, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov si, word ds:[0x0] */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->dx = (uint16_t)(0x1);               /* mov dx, 0x1 */
    cpu->cx = (uint16_t)(cpu->si);           /* mov cx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg214_0000(cpu);                        /* call 0000:13DE */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x27)) | 0x10; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x27), (uint16_t)(_r)); } /* or word ds:[si+0x27], 0x10 */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov es, word ss:[bp+-0x8] */
    cpu->ax = mem_read16(cpu, cpu->es, 0x8BC); /* les ax, word es:[0x8BC] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x8BC + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE4), (uint16_t)(cpu->ax)); /* mov word ds:[si+0xE4], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE6), (uint16_t)(cpu->es)); /* mov word ds:[si+0xE6], es */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE0), (uint16_t)(cpu->di)); /* mov word ds:[si+0xE0], di */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ax, word ss:[bp+-0x2] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE2), (uint16_t)(cpu->ax)); /* mov word ds:[si+0xE2], ax */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x6))); /* push word ss:[bp+0x6] */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x80);                       /* push 0x80 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x8))); /* mov ax, word ss:[bp+0x8] */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg214_0C9A(cpu);                        /* call 0000:FFFF */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* push word ss:[bp+-0x8] */
    cpu->ax = (uint16_t)(0x4B);              /* mov ax, 0x4B */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_32C2(cpu);                        /* call 0000:0016 */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 0x8; return;                  /* retf 0x4 */
}

void seg221_0696(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->bx);           /* mov si, bx */
    cpu->ax = (uint16_t)(0x788);             /* mov ax, 0x788 */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    push16(cpu, 0x1);                        /* push 0x1 */
    cpu->ax = (uint16_t)(0x53);              /* mov ax, 0x53 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->dx = (uint16_t)(0x142);             /* mov dx, 0x142 */
    cpu->cx = (uint16_t)(0x1EB);             /* mov cx, 0x1EB */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1C10(cpu);                        /* call 0000:0C70 */
    cpu->ax = (uint16_t)(0x8);               /* mov ax, 0x8 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1C6C(cpu);                        /* call 0000:0C78 */
    cpu->dx = (uint16_t)(SEG_58);            /* mov dx, 0x93E  /* selector for seg58 */ */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x3);               /* mov ax, 0x3 */
    /* unresolved far call call 0000:0CBF */ /* call 0000:0CBF */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x4);               /* mov ax, 0x4 */
    /* unresolved far call call 0000:06D1 */ /* call 0000:06D1 */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    /* unresolved far call call 0000:06DE */ /* call 0000:06DE */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x6);               /* mov ax, 0x6 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_1CCA(cpu);                        /* call 0000:06EB */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x3);                        /* push 0x3 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x290);             /* mov ax, 0x290 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x29C);             /* mov ax, 0x29C */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x1);                        /* push 0x1 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->dx = (uint16_t)(0x3);               /* mov dx, 0x3 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_2B4E(cpu);                        /* call 0000:0CDF */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->dx);           /* mov si, dx */
    push16(cpu, 0x3);                        /* push 0x3 */
    cpu->cx = mem_read16(cpu, cpu->ds, 0x66); /* lds cx, word ds:[0x66] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x66 + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_3DFC(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->di + 0x53)); /* lea ax, word ds:[di+0x53] */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    cpu->cx = (uint16_t)(0x2);               /* mov cx, 0x2 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg227_12B2(cpu);                        /* call 0000:0916 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ds, word ss:[bp+-0x2] */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x46) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x46, (uint16_t)(_r)); } /* and word ds:[0x46], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x48) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x48, (uint16_t)(_r)); } /* and word ds:[0x48], 0x0 */
    mem_write16(cpu, cpu->ds, 0x42, (uint16_t)(0xFF)); /* mov word ds:[0x42], 0xFF */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x44) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x44, (uint16_t)(_r)); } /* and word ds:[0x44], 0x0 */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg224_2C70(cpu);                        /* call 0000:0D22 */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_0C50(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    { int _cf = cf(cpu); cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec sp */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->bx);           /* mov si, bx */
    cpu->ax = (uint16_t)(0xD4D);             /* mov ax, 0xD4D */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    push16(cpu, 0x1);                        /* push 0x1 */
    cpu->ax = (uint16_t)(0x82);              /* mov ax, 0x82 */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->dx = (uint16_t)(0x142);             /* mov dx, 0x142 */
    cpu->cx = (uint16_t)(0x1EB);             /* mov cx, 0x1EB */
    /* unresolved far call call 0000:1788 */ /* call 0000:1788 */
    cpu->ax = (uint16_t)(0xA);               /* mov ax, 0xA */
    /* unresolved far call call 0000:1790 */ /* call 0000:1790 */
    cpu->dx = (uint16_t)(0x1495);            /* mov dx, 0x1495 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x4);               /* mov ax, 0x4 */
    /* unresolved far call call 0000:17FE */ /* call 0000:17FE */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    /* unresolved far call call 0000:0C8B */ /* call 0000:0C8B */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x6);               /* mov ax, 0x6 */
    /* unresolved far call call 0000:0C98 */ /* call 0000:0C98 */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x7);               /* mov ax, 0x7 */
    /* unresolved far call call 0000:0CA5 */ /* call 0000:0CA5 */
    cpu->bx = (uint16_t)(0x42);              /* mov bx, 0x42 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->ax = (uint16_t)(0x8);               /* mov ax, 0x8 */
    /* unresolved far call call 0000:0CB2 */ /* call 0000:0CB2 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x3);                        /* push 0x3 */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x34C);             /* mov ax, 0x34C */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->ax = (uint16_t)(0x364);             /* mov ax, 0x364 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x1);                        /* push 0x1 */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->dx = (uint16_t)(0x3);               /* mov dx, 0x3 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    /* unresolved far call call 0000:1821 */ /* call 0000:1821 */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->si = (uint16_t)(cpu->dx);           /* mov si, dx */
    push16(cpu, 0x3);                        /* push 0x3 */
    cpu->cx = mem_read16(cpu, cpu->ds, 0x9F); /* lds cx, word ds:[0x9F] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x9F + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->di + 0x53)); /* lea ax, word ds:[di+0x53] */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    cpu->cx = (uint16_t)(0x2);               /* mov cx, 0x2 */
    /* unresolved far call call 0000:1460 */ /* call 0000:1460 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov ds, word ss:[bp+-0x2] */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x46) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x46, (uint16_t)(_r)); } /* and word ds:[0x46], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x48) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x48, (uint16_t)(_r)); } /* and word ds:[0x48], 0x0 */
    mem_write16(cpu, cpu->ds, 0x42, (uint16_t)(0xFF)); /* mov word ds:[0x42], 0xFF */
    { uint16_t _r = mem_read16(cpu, cpu->ds, 0x44) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, 0x44, (uint16_t)(_r)); } /* and word ds:[0x44], 0x0 */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->si);           /* mov bx, si */
    /* unresolved far call call 0000:189A */ /* call 0000:189A */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_0D30(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x6A)); /* sub sp, 0x6A */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD2))); /* mov cx, word ds:[si+0xD2] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x6], cx */
    cpu->ax = (uint16_t)(0x1023);            /* mov ax, 0x1023 */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x8], es */
    cpu->bx = mem_read16(cpu, cpu->es, 0x87E); /* les bx, word es:[0x87E] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x87E + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->es, cpu->bx), cpu->cx); /* cmp word es:[bx], cx */
    if (cc_g(cpu)) goto L_seg221_0D30_000D62; /* jg 0x0D62 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg221_0D30_000DC3;               /* jmp 0x0DC3 */
L_seg221_0D30_000D62:;
L_seg221_0D30_000D62:;
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB0)); /* lds bx, word ds:[si+0xB0] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB0) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0xA], ds */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xC], bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x12))); /* mov ax, word ds:[bx+0x12] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xE], ax */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x10))); /* mov di, word ds:[bx+0x10] */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x10], di */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov es, word ss:[bp+-0x8] */
    push16(cpu, cpu->es);                    /* push es */
    cpu->ax = (uint16_t)(0xA3);              /* mov ax, 0xA3 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->es);                    /* push es */
    cpu->ax = (uint16_t)(0xB0);              /* mov ax, 0xB0 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x56)); /* lea ax, word ss:[bp+-0x56] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->bx = mem_read16(cpu, cpu->es, 0x87E); /* les bx, word es:[0x87E] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)(0x87E + 2));
    cpu->si = (uint16_t)(0xF);               /* mov si, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->cx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x84)); /* lea cx, word ds:[bx+si+0x84] */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    /* unresolved far call call 0000:10D2 */ /* call 0000:10D2 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x56)); /* lea ax, word ss:[bp+-0x56] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    { uint8_t _r = cpu->cl ^ cpu->cl; flags_logic8(cpu, _r); cpu->cl = (uint8_t)(_r); } /* xor cl, cl */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg188_00BC(cpu);                        /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x5A), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x5A], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x58), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x58], bx */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    { uint16_t _r = cpu->cx | cpu->ax; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* or cx, ax */
    if (cc_ne(cpu)) goto L_seg221_0D30_000DC6; /* jne 0x0DC6 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg221_0D30_000DC3:;
L_seg221_0D30_000DC3:;
    goto L_seg221_0D30_001003;               /* jmp 0x1003 */
L_seg221_0D30_000DC6:;
L_seg221_0D30_000DC6:;
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x6);                        /* push 0x6 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x5E), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x5E], bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x5C), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x5C], ds */
    cpu->ax = (uint16_t)(0x13B3);            /* mov ax, 0x13B3 */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x60), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x60], es */
    cpu->ax = (uint16_t)(cpu->ds);           /* mov ax, ds */
    { uint16_t _r = cpu->ax | cpu->bx; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, bx */
    if (cc_e(cpu)) goto L_seg221_0D30_000E27; /* je 0x0E27 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, 0)); /* mov ax, word es:[0x0] */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_sub16(cpu, cpu->cx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xA)))); /* sub cx, word ds:[bx+0xA] */
    cpu->ax = (uint16_t)(0x2);               /* mov ax, 0x2 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->cx); cpu->cx = (uint16_t)(_t); } /* xchg ax, cx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->cx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->cx); cpu->cx = (uint16_t)(_t); } /* xchg ax, cx */
    { int _cf = cf(cpu); cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc cx */
    cpu->di = (uint16_t)(flags_sub16(cpu, cpu->di, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xC)))); /* sub di, word ds:[bx+0xC] */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 0xFFF8)); /* add di, 0xFFF8 */
    cpu->ax = (uint16_t)(0x2);               /* mov ax, 0x2 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->di; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv di */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
    push16(cpu, cpu->cx);                    /* push cx */
    push16(cpu, cpu->di);                    /* push di */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov ax, word ss:[bp+-0xC] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov bx, word ss:[bp+-0xA] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x5E)); /* lea ax, word ss:[bp+-0x5E] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg221_0D30_000E27:;
L_seg221_0D30_000E27:;
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0x56E)); /* mov ax, word ds:[0x56E] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x62], ax */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x64), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x64], ax */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds si, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x1))); /* mov al, byte es:[bx+0x1] */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x65), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x65], al */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x3))); /* mov al, byte es:[bx+0x3] */
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x66), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x66], al */
    cpu->ax = (uint16_t)(0xDDE);             /* mov ax, 0xDDE */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, 0x16)); /* mov al, byte es:[0x16] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    if (cc_ne(cpu)) goto L_seg221_0D30_000E71; /* jne 0x0E71 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    goto L_seg221_0D30_000E76;               /* jmp 0x0E76 */
L_seg221_0D30_000E71:;
L_seg221_0D30_000E71:;
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 0x3)); /* add cx, 0x3 */
L_seg221_0D30_000E76:;
L_seg221_0D30_000E76:;
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les bx, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x3), (uint8_t)(cpu->cl)); /* mov byte es:[bx+0x3], cl */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x1)) & cpu->ch); /* test byte ss:[bp+0x1], ch */
    cpu->bl = (uint8_t)(cpu->al);            /* mov bl, al */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
L_seg221_0D30_000E8B:;
L_seg221_0D30_000E8B:;
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x67), (uint8_t)(cpu->bl)); /* mov byte ss:[bp+-0x67], bl */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xD6)), 0x0); /* cmp word ds:[si+0xD6], 0x0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x1)) & cpu->ah); /* test byte ss:[bp+0x1], ah */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
L_seg221_0D30_000E99:;
L_seg221_0D30_000E99:;
    mem_write8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x68), (uint8_t)(cpu->al)); /* mov byte ss:[bp+-0x68], al */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x60))); /* mov ds, word ss:[bp+-0x60] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->dx = (uint16_t)(0x2);               /* mov dx, 0x2 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov ax, word ss:[bp+-0xC] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov bx, word ss:[bp+-0xA] */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->bx = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xB4)); /* les bx, word es:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x67))); /* mov al, byte ss:[bp+-0x67] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[bx+0x1], al */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->bx = (uint16_t)(0x1040);            /* mov bx, 0x1040 */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6A), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x6A], es */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov ds, word ss:[bp+-0x8] */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x87E); /* lds bx, word ds:[0x87E] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)(0x87E + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov cx, word ss:[bp+-0x6] */
    cpu->di = (uint16_t)(0xF);               /* mov di, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->cx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->bx = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x84)); /* lea bx, word ds:[bx+di+0x84] */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, mem_read16(cpu, cpu->es, 0x4))); /* sub ax, word es:[0x4] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov bx, word ss:[bp+-0xA] */
    push16(cpu, cpu->bx);                    /* push bx */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov cx, word ss:[bp+-0xC] */
    push16(cpu, cpu->cx);                    /* push cx */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x10)); /* add sp, 0x10 */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x60))); /* mov ds, word ss:[bp+-0x60] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->di = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xB4)); /* les di, word es:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x68))); /* mov al, byte ss:[bp+-0x68] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[di+0x1], al */
    cpu->ax = (uint16_t)(0x12);              /* mov ax, 0x12 */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov di, word ds:[0x0] */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* push word ss:[bp+-0x8] */
    cpu->dx = (uint16_t)(0xBA);              /* mov dx, 0xBA */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov dx, word ss:[bp+-0xE] */
    cpu->dx = (uint16_t)(flags_sub16(cpu, cpu->dx, cpu->di)); /* sub dx, di */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->cx);                    /* push cx */
    /* unresolved far call call 0000:0EFF */ /* call 0000:0EFF */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x10)); /* add sp, 0x10 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov bx, word ds:[0x0] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6A))); /* mov es, word ss:[bp+-0x6A] */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, mem_read16(cpu, cpu->es, 0x4))); /* add ax, word es:[0x4] */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov es, word ss:[bp+-0x2] */
    cpu->si = mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0xB4)); /* les si, word es:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->es, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->bl = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x67))); /* mov bl, byte ss:[bp+-0x67] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->si + 0x1), (uint8_t)(cpu->bl)); /* mov byte es:[si+0x1], bl */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov di, word ds:[0x0] */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov ds, word ss:[bp+-0x8] */
    cpu->bx = mem_read16(cpu, cpu->ds, 0x87E); /* les bx, word ds:[0x87E] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)(0x87E + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov cx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(0xF);               /* mov si, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->cx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->cx = (uint16_t)(0x3C);              /* mov cx, 0x3C */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x91))); /* mov bx, word es:[bx+si+0x91] */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    { int32_t _n = (int32_t)(((uint32_t)cpu->dx << 16) | cpu->ax); int16_t _d = (int16_t)cpu->cx; cpu->ax = (uint16_t)(int16_t)(_n / _d); cpu->dx = (uint16_t)(int16_t)(_n % _d); } /* idiv cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->bx); cpu->bx = (uint16_t)(_t); } /* xchg ax, bx */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ds);                    /* push ds */
    cpu->bx = (uint16_t)(0xBF);              /* mov bx, 0xBF */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov bx, word ss:[bp+-0xE] */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->di)); /* sub bx, di */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* push word ss:[bp+-0xA] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov bx, word ss:[bp+-0xC] */
    push16(cpu, cpu->bx);                    /* push bx */
    /* unresolved far call call 0000:0F36 */ /* call 0000:0F36 */
    cpu->sp = (uint16_t)(flags_add16(cpu, cpu->sp, 0x12)); /* add sp, 0x12 */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds si, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->di = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les di, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x66))); /* mov al, byte ss:[bp+-0x66] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x3), (uint8_t)(cpu->al)); /* mov byte es:[di+0x3], al */
    cpu->di = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* les di, word ds:[si+0xB4] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x65))); /* mov al, byte ss:[bp+-0x65] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->di + 0x1), (uint8_t)(cpu->al)); /* mov byte es:[di+0x1], al */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x64))); /* mov ax, word ss:[bp+-0x64] */
    /* unresolved far call call 0000:0E3A */ /* call 0000:0E3A */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x62))); /* mov ax, word ss:[bp+-0x62] */
    /* unresolved far call call 0000:0E30 */ /* call 0000:0E30 */
    cpu->es = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov es, word ss:[bp+-0xA] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x12))); /* mov ax, word es:[bx+0x12] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x10))); /* mov ax, word es:[bx+0x10] */
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->si = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xB4)); /* lds si, word ds:[si+0xB4] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si + 0xB4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x3))); /* mov al, byte ds:[si+0x3] */
    push16(cpu, cpu->ax);                    /* push ax */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x5A)); /* lea ax, word ss:[bp+-0x5A] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    goto L_seg221_0D30_001003;               /* jmp 0x1003 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bx = (uint16_t)(flags_add16(cpu, cpu->bx, 0xF)); /* add bx, 0xF */
    goto L_seg221_0D30_000E8B;               /* jmp 0x0E8B */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0x3)); /* add ax, 0x3 */
    goto L_seg221_0D30_000E99;               /* jmp 0x0E99 */
L_seg221_0D30_001003:;
L_seg221_0D30_001003:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_100A(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x54)); /* sub sp, 0x54 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x2), (uint16_t)(0x3C)); /* mov word ds:[si+0x2], 0x3C */
    cpu->dx = (uint16_t)(0x11B8);            /* mov dx, 0x11B8 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x6], dx */
    cpu->cx = (uint16_t)(0xC3);              /* mov cx, 0xC3 */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg200_057B(cpu);                        /* call 0000:11E7 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x8], dx */
    { uint16_t _r = cpu->dx | cpu->ax; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* or dx, ax */
    if (cc_ne(cpu)) goto L_seg221_100A_00103F; /* jne 0x103F */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg221_100A_001151;               /* jmp 0x1151 */
L_seg221_100A_00103F:;
L_seg221_100A_00103F:;
    cpu->ax = (uint16_t)(0xFFFF);            /* mov ax, 0xFFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xC], ax */
L_seg221_100A_001045:;
L_seg221_100A_001045:;
    goto L_seg221_100A_00110E;               /* jmp 0x110E */
    cpu->ax = (uint16_t)(0x68F);             /* mov ax, 0x68F */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg134_00E0(cpu);                        /* call 0000:FFFF */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, cpu->si), 0x0); /* cmp byte es:[si], 0x0 */
    if (cc_e(cpu)) goto L_seg221_100A_001045; /* je 0x1045 */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, cpu->si), 0x3B); /* cmp byte es:[si], 0x3B */
    if (cc_e(cpu)) goto L_seg221_100A_001045; /* je 0x1045 */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, cpu->si), 0x23); /* cmp byte es:[si], 0x23 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->si + 0x2600)) & cpu->dl); /* test byte ss:[bp+si+0x2600], dl */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, cpu->si), 0x30); /* cmp byte ds:[si], 0x30 */
    /* jl out of function to 0x001078 */     /* jl 0x1078 */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, cpu->si), 0x39); /* cmp byte es:[si], 0x39 */
    /* data byte: 0x0F */                    /* db 0xF */
    cpu->es = (uint16_t)(cpu->sp);           /* mov es, sp */
    cpu->ch = (uint8_t)(flags_add8(cpu, cpu->ch, cpu->al)); /* add ch, al */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->flags &= ~FLAG_DF;                  /* cld */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x2))); /* mov ax, word ds:[bx+0x2] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xE], ax */
L_seg221_100A_001081:;
L_seg221_100A_001081:;
    flags_cmp16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE)), 0xA); /* cmp word ss:[bp+-0xE], 0xA */
    if (cc_ge(cpu)) goto L_seg221_100A_00108C; /* jge 0x108C */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(0xA)); /* mov word ss:[bp+-0xE], 0xA */
L_seg221_100A_00108C:;
L_seg221_100A_00108C:;
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    cpu->di = (uint16_t)(0xF);               /* mov di, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->di; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul di */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x84)); /* lea ax, word ds:[bx+di+0x84] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->cx = (uint16_t)(cpu->si);           /* mov cx, si */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg173_0404(cpu);                        /* call 0000:FFFF */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->bx = (uint16_t)(0xC6);              /* mov bx, 0xC6 */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->ax = (uint16_t)(0xD3);              /* mov ax, 0xD3 */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, 0x0);                        /* push 0x0 */
    cpu->di = (uint16_t)((uint16_t)(cpu->bp - 0x54)); /* lea di, word ss:[bp+-0x54] */
    push16(cpu, cpu->ss);                    /* push ss */
    cpu->es = (uint16_t)(pop16(cpu));        /* pop es */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    cpu->si = (uint16_t)(0xF);               /* mov si, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->si; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul si */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x84)); /* lea cx, word ds:[bx+si+0x84] */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    /* unresolved far call call 0000:214E */ /* call 0000:214E */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0x54)); /* lea ax, word ss:[bp+-0x54] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg139_0060(cpu);                        /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg221_100A_00110E; /* je 0x110E */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov ax, word ss:[bp+-0xE] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov cx, word ds:[bx] */
    cpu->si = (uint16_t)(0xF);               /* mov si, 0xF */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->cx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul cx */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->si); cpu->si = (uint16_t)(_t); } /* xchg ax, si */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x91), (uint16_t)(cpu->ax)); /* mov word ds:[bx+si+0x91], ax */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ds, cpu->bx, (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, cpu->bx), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ds:[bx] */
    goto L_seg221_100A_00110E;               /* jmp 0x110E */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + 0x2)); /* lea ax, word ds:[bx+0x2] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    cpu->cx = (uint16_t)(cpu->si);           /* mov cx, si */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
L_seg221_100A_00110E:;
L_seg221_100A_00110E:;
    cpu->ax = (uint16_t)(0x68F);             /* mov ax, 0x68F */
    cpu->ds = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov ds, word ss:[bp+-0xC] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov di, word ss:[bp+-0xA] */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov si, word ss:[bp+-0x8] */
    cpu->dx = (uint16_t)(cpu->si);           /* mov dx, si */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg126_0000(cpu);                        /* call 0000:FFFF */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, cpu->di) & cpu->bl); /* test byte ds:[di], bl */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x7439), (uint16_t)(flags_sub16(cpu, mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x7439)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec word ss:[bp+di+-0x7439] */
    /* FPU TODO: ficomp word word ss:[bp+si+0x128D] word ss:[bp+si+0x128D] */ /* ficomp word word ss:[bp+si+0x128D] word ss:[bp+si+0x128D] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si)), cpu->al))); /* add byte ds:[bx+si], al */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, cpu->bx)); /* mov ax, word ds:[bx] */
    goto L_seg221_100A_001151;               /* jmp 0x1151 */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bp - 0xE)); /* lea ax, word ss:[bp+-0xE] */
    cpu->bx = (uint16_t)(cpu->ss);           /* mov bx, ss */
    cpu->cx = (uint16_t)(cpu->si);           /* mov cx, si */
    cpu->dx = (uint16_t)(cpu->es);           /* mov dx, es */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg148_02AA(cpu);                        /* call 0000:110A */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    goto L_seg221_100A_001081;               /* jmp 0x1081 */
L_seg221_100A_001151:;
L_seg221_100A_001151:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg221_1156(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x2], bx */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    { uint16_t _r = cpu->ax | cpu->cx; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, cx */
    if (cc_ne(cpu)) goto L_seg221_1156_001173; /* jne 0x1173 */
    { uint16_t _r = cpu->bx | cpu->si; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, si */
    if (cc_ne(cpu)) goto L_seg221_1156_001181; /* jne 0x1181 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg221_1156_0011A0;               /* jmp 0x11A0 */
L_seg221_1156_001173:;
L_seg221_1156_001173:;
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    /* unresolved far call call 0000:242C */ /* call 0000:242C */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    cpu->dx = (cpu->ax & 0x8000) ? 0xFFFF : 0x0000; /* cwd */
    goto L_seg221_1156_0011A0;               /* jmp 0x11A0 */
L_seg221_1156_001181:;
L_seg221_1156_001181:;
    cpu->bl = (uint8_t)(0xFF);               /* mov bl, 0xFF */
    cpu->ax = (uint16_t)(0x804);             /* mov ax, 0x804 */
    /* unresolved far call call 0000:2362 */ /* call 0000:2362 */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg221_100A(cpu);                        /* call 0x100A */
    cpu->ax = (uint16_t)(cpu->di);           /* mov ax, di */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
L_seg221_1156_0011A0:;
L_seg221_1156_0011A0:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

