/* Segment 217 - 6157 bytes, 11 functions */
/* Auto-generated by ne_lift.py - El-Fish Recomp */

#include "cpu.h"
#include "fpu.h"
#include <math.h>

void seg217_0000(CPU *cpu);
void seg217_00A6(CPU *cpu);
void seg217_0562(CPU *cpu);
void seg217_05C8(CPU *cpu);
void seg217_0996(CPU *cpu);
void seg217_0CBE(CPU *cpu);
void seg217_0E5A(CPU *cpu);
void seg217_0EAE(CPU *cpu);
void seg217_0F3E(CPU *cpu);
void seg217_106C(CPU *cpu);
void seg217_12DC(CPU *cpu);

void seg217_0000(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8)); /* sub sp, 0x8 */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    cpu->dx = (uint16_t)(cpu->bx);           /* mov dx, bx */
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov bx, word ss:[bp+-0x8] */
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx + cpu->si)); /* lea ax, word ds:[bx+si] */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_00A6(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8)); /* sub sp, 0x8 */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x6], bx */
    cpu->dx = (uint16_t)(0x0);               /* mov dx, 0x0 */
    cpu->si = (uint16_t)(0x0);               /* mov si, 0x0 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->cx)); /* sub bx, cx */
    cpu->dx = (uint16_t)(flags_sub16(cpu, cpu->dx, cpu->si + cf(cpu))); /* sbb dx, si */
    flags_cmp16(cpu, cpu->ax, cpu->cx);      /* cmp ax, cx */
    if (cc_be(cpu)) goto L_seg217_00A6_0000C7; /* jbe 0x00C7 */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    goto L_seg217_00A6_0000C9;               /* jmp 0x00C9 */
L_seg217_00A6_0000C7:;
L_seg217_00A6_0000C7:;
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
L_seg217_00A6_0000C9:;
L_seg217_00A6_0000C9:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0562(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->bx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x1A2)); /* les bx, word ds:[bx+di+0x1A2] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0x1A2) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, cpu->bx)); /* mov al, byte es:[bx] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->cx = (uint16_t)(0x1);               /* mov cx, 0x1 */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x1A2), (uint16_t)(cpu->ax)); /* mov word ds:[bx+di+0x1A2], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x1A4), (uint16_t)(cpu->dx)); /* mov word ds:[bx+di+0x1A4], dx */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_05C8(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0xA)); /* sub sp, 0xA */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x2], cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0x4], bx */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(_r)); } /* and word ss:[bp+-0xA], 0x0 */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    cpu->si = (uint16_t)(0x4);               /* mov si, 0x4 */
    goto L_seg217_05C8_0005EA;               /* jmp 0x05EA */
L_seg217_05C8_0005E4:;
L_seg217_05C8_0005E4:;
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
L_seg217_05C8_0005E6:;
L_seg217_05C8_0005E6:;
    flags_logic16(cpu, cpu->si & cpu->si);   /* test si, si */
    if (cc_e(cpu)) goto L_seg217_05C8_00061B; /* je 0x061B */
L_seg217_05C8_0005EA:;
L_seg217_05C8_0005EA:;
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov cx, word ss:[bp+-0x2] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    cpu->cl = (uint8_t)(0x7);                /* mov cl, 0x7 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ax, word ss:[bp+-0xA] */
    /* unresolved far call call 0000:0739 */ /* call 0000:0739 */
    cpu->bx = (uint16_t)(0x0);               /* mov bx, 0x0 */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    { uint16_t _r = cpu->cx & 0x7F; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* and cx, 0x7F */
    { uint16_t _r = cpu->ax | cpu->cx; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, cx */
    { uint16_t _r = cpu->dx | cpu->bx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* or dx, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    flags_logic16(cpu, cpu->di & 0x80);      /* test di, 0x80 */
    if (cc_e(cpu)) goto L_seg217_05C8_0005E4; /* je 0x05E4 */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_sub16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* dec si */
    goto L_seg217_05C8_0005E6;               /* jmp 0x05E6 */
L_seg217_05C8_00061B:;
L_seg217_05C8_00061B:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0996(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0xE)); /* sub sp, 0xE */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x2], di */
    cpu->dx = (uint16_t)(cpu->ax);           /* mov dx, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x6], dx */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_05A6(cpu);                        /* call 0x05A6 */
    flags_cmp16(cpu, cpu->ax, 0x80);         /* cmp ax, 0x80 */
    if (cc_b(cpu)) goto L_seg217_0996_0009CC; /* jb 0x09CC */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->dx);           /* mov ax, dx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2A2), (uint8_t)(cpu->al)); /* mov byte ds:[bx+di+0x2A2], al */
L_seg217_0996_0009CC:;
L_seg217_0996_0009CC:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2A2)), 0x80); /* cmp byte ds:[bx+di+0x2A2], 0x80 */
    if (cc_ae(cpu)) goto L_seg217_0996_0009DC; /* jae 0x09DC */
    cpu->ax = (uint16_t)(0x5);               /* mov ax, 0x5 */
    goto L_seg217_0996_000BE1;               /* jmp 0x0BE1 */
L_seg217_0996_0009DC:;
L_seg217_0996_0009DC:;
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(_r)); } /* and word ds:[bx+0x196], 0x0 */
    { uint16_t _r = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)) & 0x0; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(_r)); } /* and word ds:[bx+0x198], 0x0 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x1))); /* add word ds:[bx+0x196], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), 0x0 + cf(cpu)))); /* adc word ds:[bx+0x198], 0x0 */
L_seg217_0996_0009F0:;
L_seg217_0996_0009F0:;
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2A2))); /* mov al, byte ds:[bx+di+0x2A2] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15), (uint8_t)(cpu->al)); /* mov byte ds:[bx+si+0x15], al */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2A2))); /* mov al, byte ds:[bx+di+0x2A2] */
    { uint8_t _r = cpu->al & 0xF0; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* and al, 0xF0 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xF0)); /* sub bx, 0xF0 */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di - 0x7D00)) & cpu->dl); /* test byte ds:[bx+di+-0x7D00], dl */
    goto L_seg217_0996_0009F0;               /* jmp 0x09F0 */
    if (cc_e(cpu)) goto L_seg217_0996_000A51; /* je 0x0A51 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF0)); /* sub bx, 0xFFF0 */
    if (cc_e(cpu)) goto L_seg217_0996_000A51; /* je 0x0A51 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0x20)); /* sub bx, 0x20 */
    if (cc_e(cpu)) goto L_seg217_0996_000A30; /* je 0x0A30 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFD0)); /* sub bx, 0xFFD0 */
    if (cc_e(cpu)) goto L_seg217_0996_000A30; /* je 0x0A30 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF0)); /* sub bx, 0xFFF0 */
    if (cc_e(cpu)) goto L_seg217_0996_000A30; /* je 0x0A30 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF0)); /* sub bx, 0xFFF0 */
    if (cc_e(cpu)) goto L_seg217_0996_000A30; /* je 0x0A30 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF0)); /* sub bx, 0xFFF0 */
    if (cc_ne(cpu)) goto L_seg217_0996_000A72; /* jne 0x0A72 */
L_seg217_0996_000A30:;
L_seg217_0996_000A30:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x1))); /* add word ds:[bx+0x196], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), 0x0 + cf(cpu)))); /* adc word ds:[bx+0x198], 0x0 */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15), (uint8_t)(cpu->al)); /* mov byte ds:[bx+si+0x15], al */
L_seg217_0996_000A51:;
L_seg217_0996_000A51:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x1))); /* add word ds:[bx+0x196], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), 0x0 + cf(cpu)))); /* adc word ds:[bx+0x198], 0x0 */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15), (uint8_t)(cpu->al)); /* mov byte ds:[bx+si+0x15], al */
L_seg217_0996_000A72:;
L_seg217_0996_000A72:;
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov si, word ss:[bp+-0x2] */
    cpu->cx = (uint16_t)(cpu->si);           /* mov cx, si */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_05C8(cpu);                        /* call 0x05C8 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x322), (uint16_t)(cpu->ax)); /* mov word ds:[bx+si+0x322], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x324), (uint16_t)(cpu->dx)); /* mov word ds:[bx+si+0x324], dx */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x16))); /* mov al, byte ds:[bx+0x16] */
    { uint8_t _r = cpu->al & 0xF; flags_logic8(cpu, _r); cpu->al = (uint8_t)(_r); } /* and al, 0xF */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x19E), (uint16_t)(cpu->ax)); /* mov word ds:[bx+0x19E], ax */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg217_0996_000ABC;               /* jmp 0x0ABC */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2A2))); /* mov al, byte ds:[bx+di+0x2A2] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xF7)); /* sub bx, 0xF7 */
    if (cc_e(cpu)) goto L_seg217_0996_000AF6; /* je 0x0AF6 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF9)); /* sub bx, 0xFFF9 */
    if (cc_e(cpu)) goto L_seg217_0996_000AF6; /* je 0x0AF6 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xF)); /* sub bx, 0xF */
    if (cc_e(cpu)) goto L_seg217_0996_000ABF; /* je 0x0ABF */
    cpu->ax = (uint16_t)(0x4);               /* mov ax, 0x4 */
L_seg217_0996_000ABC:;
L_seg217_0996_000ABC:;
    goto L_seg217_0996_000BE1;               /* jmp 0x0BE1 */
L_seg217_0996_000ABF:;
L_seg217_0996_000ABF:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x1))); /* add word ds:[bx+0x196], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), 0x0 + cf(cpu)))); /* adc word ds:[bx+0x198], 0x0 */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15), (uint8_t)(cpu->al)); /* mov byte ds:[bx+si+0x15], al */
    cpu->bx = (uint16_t)(cpu->cx);           /* mov bx, cx */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0x51)); /* sub bx, 0x51 */
    if (cc_e(cpu)) goto L_seg217_0996_000B30; /* je 0x0B30 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFDE)); /* sub bx, 0xFFDE */
    if (cc_ne(cpu)) goto L_seg217_0996_000AF6; /* jne 0x0AF6 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x2E2), (uint8_t)(0x0)); /* mov byte ds:[bx+di+0x2E2], 0x0 */
L_seg217_0996_000AF6:;
L_seg217_0996_000AF6:;
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov ax, word ss:[bp+-0x6] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_05C8(cpu);                        /* call 0x05C8 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xE], ax */
    cpu->di = (uint16_t)(cpu->dx);           /* mov di, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0xC], di */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    cpu->cx = (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x16)); /* lea cx, word ds:[bx+si+0x16] */
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->di);           /* mov bx, di */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_063C(cpu);                        /* call 0x063C */
    cpu->cx = (uint16_t)(0x0);               /* mov cx, 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), cpu->ax))); /* add word ds:[bx+0x196], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), cpu->cx + cf(cpu)))); /* adc word ds:[bx+0x198], cx */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    goto L_seg217_0996_000BC1;               /* jmp 0x0BC1 */
L_seg217_0996_000B30:;
L_seg217_0996_000B30:;
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x1A2)); /* les ax, word ds:[bx+si+0x1A2] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0x1A2) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x8], es */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0xA], ax */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov si, word ss:[bp+-0x6] */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_05C8(cpu);                        /* call 0x05C8 */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_06E0(cpu);                        /* call 0x06E0 */
    push16(cpu, 0x0);                        /* push 0x0 */
    push16(cpu, 0x64);                       /* push 0x64 */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg155_0000(cpu);                        /* call 0000:0DD0 */
    cpu->bx = (uint16_t)(0x0);               /* mov bx, 0x0 */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x10))); /* mov cx, word ds:[si+0x10] */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->ax);                    /* push ax */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->cx);                    /* push cx */
    /* unresolved far call call 0000:0CF0 */ /* call 0000:0CF0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x12), (uint16_t)(cpu->ax)); /* mov word ds:[bx+0x12], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x14), (uint16_t)(cpu->dx)); /* mov word ds:[bx+0x14], dx */
    cpu->si = (uint16_t)(cpu->di);           /* mov si, di */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ax, word ss:[bp+-0xA] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x1A2), (uint16_t)(cpu->ax)); /* mov word ds:[bx+si+0x1A2], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov ax, word ss:[bp+-0x8] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x1A4), (uint16_t)(cpu->ax)); /* mov word ds:[bx+si+0x1A4], ax */
    goto L_seg217_0996_000AF6;               /* jmp 0x0AF6 */
L_seg217_0996_000B94:;
L_seg217_0996_000B94:;
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x180); /* cmp word ds:[bx+0x196], 0x180 */
    if (cc_ae(cpu)) goto L_seg217_0996_000BDE; /* jae 0x0BDE */
L_seg217_0996_000B9C:;
L_seg217_0996_000B9C:;
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196)), 0x1))); /* add word ds:[bx+0x196], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x198)), 0x0 + cf(cpu)))); /* adc word ds:[bx+0x198], 0x0 */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov cx, word ss:[bp+-0x2] */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0562(cpu);                        /* call 0x0562 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov bx, word ss:[bp+-0x6] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x196))); /* mov si, word ds:[bx+0x196] */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x15), (uint8_t)(cpu->al)); /* mov byte ds:[bx+si+0x15], al */
    cpu->dx = (uint16_t)(flags_add16(cpu, cpu->dx, 0x1)); /* add dx, 0x1 */
    cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 0x0 + cf(cpu))); /* adc di, 0x0 */
L_seg217_0996_000BC1:;
L_seg217_0996_000BC1:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov ax, word ss:[bp+-0xE] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov cx, word ss:[bp+-0xC] */
    flags_cmp16(cpu, cpu->di, cpu->cx);      /* cmp di, cx */
    /* jb out of function to 0x000BD5 */     /* jb 0x0BD5 */
    /* data byte: 0x0F */                    /* db 0xF */
    { uint16_t _t = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di + 0x3BFE)); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di + 0x3BFE), (uint16_t)(cpu->sp)); cpu->sp = (uint16_t)(_t); } /* xchg word ss:[bp+di+0x3BFE], sp */
    /* TODO: ror mem_read8(cpu, cpu->ds, cpu->bx), 0x1 */ /* ror byte ds:[bx], 0x1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->di - 0x7C02), (uint16_t)(flags_sub16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->di - 0x7C02)), 0xFFBF + cf(cpu)))); /* sbb word ds:[di+-0x7C02], 0xFFBF */
    cpu->ax = (uint16_t)(int16_t)(int8_t)cpu->al; /* cbw */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si)), cpu->ax))); /* add word ds:[bx+si], ax */
    if (cc_b(cpu)) goto L_seg217_0996_000B9C; /* jb 0x0B9C */
    if (cc_be(cpu)) goto L_seg217_0996_000B94; /* jbe 0x0B94 */
L_seg217_0996_000BDE:;
L_seg217_0996_000BDE:;
    cpu->ax = (uint16_t)(0x3);               /* mov ax, 0x3 */
L_seg217_0996_000BE1:;
L_seg217_0996_000BE1:;
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0CBE(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x4], di */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x182), (uint16_t)(cpu->si)); /* mov word es:[di+0x182], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x484), (uint16_t)(cpu->si)); /* mov word es:[di+0x484], si */
    cpu->bx = (uint16_t)(0x0);               /* mov bx, 0x0 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->di + 0x180))); /* mov ax, word es:[di+0x180] */
    push16(cpu, 0x5F5);                      /* push 0x5F5 */
    push16(cpu, 0xE100);                     /* push 0xE100 */
    push16(cpu, cpu->bx);                    /* push bx */
    push16(cpu, cpu->ax);                    /* push ax */
    /* unresolved far call call 0000:FFFF */ /* call 0000:FFFF */
    mem_write16(cpu, cpu->es, cpu->di, (uint16_t)(cpu->ax)); /* mov word es:[di], ax */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x2), (uint16_t)(cpu->dx)); /* mov word es:[di+0x2], dx */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x4), (uint16_t)(cpu->si)); /* mov word es:[di+0x4], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x6), (uint16_t)(cpu->si)); /* mov word es:[di+0x6], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0x8), (uint16_t)(cpu->si)); /* mov word es:[di+0x8], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0xA), (uint16_t)(cpu->si)); /* mov word es:[di+0xA], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0xC), (uint16_t)(cpu->si)); /* mov word es:[di+0xC], si */
    mem_write16(cpu, cpu->es, (uint16_t)(cpu->di + 0xE), (uint16_t)(cpu->si)); /* mov word es:[di+0xE], si */
    cpu->bx = (uint16_t)(0x20);              /* mov bx, 0x20 */
    cpu->al = (uint8_t)(0xFF);               /* mov al, 0xFF */
    cpu->di = (uint16_t)((uint16_t)(cpu->di + 0x10)); /* lea di, word ds:[di+0x10] */
    cpu->ah = (uint8_t)(cpu->al);            /* mov ah, al */
    cpu->cx = (uint16_t)(0x10);              /* mov cx, 0x10 */
    while (cpu->cx != 0) { cpu->cx--;        /* rep stosw */
        mem_write16(cpu, cpu->es, cpu->di, cpu->ax); cpu->di += df(cpu) ? -2 : 2; /* stosw */
    }
L_seg217_0CBE_000D22:;
L_seg217_0CBE_000D22:;
    cpu->di = (uint16_t)(cpu->si);           /* mov di, si */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds bx, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x160), (uint16_t)(cpu->cx)); /* mov word ds:[bx+di+0x160], cx */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x150), (uint8_t)(0x0)); /* mov byte ds:[bx+si+0x150], 0x0 */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    flags_cmp16(cpu, cpu->si, 0x10);         /* cmp si, 0x10 */
    if (cc_b(cpu)) goto L_seg217_0CBE_000D22; /* jb 0x0D22 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x172), (uint16_t)(0x7F)); /* mov word ds:[bx+0x172], 0x7F */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B76))); /* mov ax, word ds:[bx+-0x7B76] */
    push16(cpu, cpu->cs); push16(cpu, 0);    /* far call return addr */
    seg209_104E(cpu);                        /* call 0000:16D1 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6E), (uint16_t)(cpu->ax)); /* mov word ds:[bx+-0x7B6E], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6C), (uint16_t)(cpu->dx)); /* mov word ds:[bx+-0x7B6C], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6E))); /* mov ax, word ds:[bx+-0x7B6E] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6C))); /* mov dx, word ds:[bx+-0x7B6C] */
    flags_logic16(cpu, cpu->dx & cpu->dx);   /* test dx, dx */
    if (cc_b(cpu)) goto L_seg217_0CBE_000D71; /* jb 0x0D71 */
    if (cc_a(cpu)) goto L_seg217_0CBE_000D63; /* ja 0x0D63 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_be(cpu)) goto L_seg217_0CBE_000D71; /* jbe 0x0D71 */
L_seg217_0CBE_000D63:;
L_seg217_0CBE_000D63:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->bx - 0x7B7A)); /* lea ax, word ds:[bx+-0x7B7A] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_028C(cpu);                        /* call 0x028C */
    cpu->ax = (uint16_t)(cpu->cx);           /* mov ax, cx */
    goto L_seg217_0CBE_000D83;               /* jmp 0x0D83 */
L_seg217_0CBE_000D71:;
L_seg217_0CBE_000D71:;
    cpu->bx = (uint16_t)(0x2);               /* mov bx, 0x2 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_00CC(cpu);                        /* call 0x00CC */
    cpu->ax = (uint16_t)(0x12EB);            /* mov ax, 0x12EB */
    cpu->ds = (uint16_t)(cpu->ax);           /* mov ds, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, 0)); /* mov ax, word ds:[0x0] */
L_seg217_0CBE_000D83:;
L_seg217_0CBE_000D83:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0E5A(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x4], cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x2], dx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xE))); /* mov ax, word ds:[si+0xE] */
    { uint16_t _r = cpu->ax | mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0xC)); flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* or ax, word ds:[si+0xC] */
    if (cc_e(cpu)) goto L_seg217_0E5A_000E7D; /* je 0x0E7D */
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0E0C(cpu);                        /* call 0x0E0C */
L_seg217_0E5A_000E7D:;
L_seg217_0E5A_000E7D:;
    { uint16_t _r = cpu->di ^ cpu->di; flags_logic16(cpu, _r); cpu->di = (uint16_t)(_r); } /* xor di, di */
    goto L_seg217_0E5A_000E93;               /* jmp 0x0E93 */
L_seg217_0E5A_000E82:;
L_seg217_0E5A_000E82:;
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->di + 0x16))); /* mov al, byte es:[bx+di+0x16] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->bx = (uint16_t)((uint16_t)(cpu->si - 0x7B7A)); /* lea bx, word ds:[si+-0x7B7A] */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0536(cpu);                        /* call 0x0536 */
    { int _cf = cf(cpu); cpu->di = (uint16_t)(flags_add16(cpu, cpu->di, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc di */
L_seg217_0E5A_000E93:;
L_seg217_0E5A_000E93:;
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les bx, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    flags_cmp16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x198)), cpu->ax); /* cmp word es:[bx+0x198], ax */
    if (cc_b(cpu)) goto L_seg217_0E5A_000EA9; /* jb 0x0EA9 */
    if (cc_a(cpu)) goto L_seg217_0E5A_000E82; /* ja 0x0E82 */
    flags_cmp16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x196)), cpu->di); /* cmp word es:[bx+0x196], di */
    if (cc_a(cpu)) goto L_seg217_0E5A_000E82; /* ja 0x0E82 */
L_seg217_0E5A_000EA9:;
L_seg217_0E5A_000EA9:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0EAE(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x8)); /* sub sp, 0x8 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x4], cx */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x8], si */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x6], ds */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x182))); /* mov si, word ds:[si+0x182] */
    flags_cmp16(cpu, cpu->si, 0x80);         /* cmp si, 0x80 */
    if (cc_ae(cpu)) goto L_seg217_0EAE_000ED7; /* jae 0x0ED7 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg217_0EAE_000EDD;               /* jmp 0x0EDD */
L_seg217_0EAE_000ED7:;
L_seg217_0EAE_000ED7:;
    cpu->ax = (uint16_t)(0xA);               /* mov ax, 0xA */
    goto L_seg217_0EAE_000F39;               /* jmp 0x0F39 */
L_seg217_0EAE_000EDC:;
L_seg217_0EAE_000EDC:;
    { int _cf = cf(cpu); cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc ax */
L_seg217_0EAE_000EDD:;
L_seg217_0EAE_000EDD:;
    flags_cmp16(cpu, cpu->ax, cpu->si);      /* cmp ax, si */
    if (cc_ae(cpu)) goto L_seg217_0EAE_000EFF; /* jae 0x0EFF */
    cpu->di = (uint16_t)(0x6);               /* mov di, 0x6 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->di; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul di */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->cl = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + 0x18))); /* mov cl, byte es:[bx+0x18] */
    cpu->ch = (uint8_t)(flags_sub8(cpu, cpu->ch, cpu->ch)); /* sub ch, ch */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov bx, word ss:[bp+-0x8] */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x184)), cpu->cx); /* cmp word ds:[bx+di+0x184], cx */
    if (cc_ne(cpu)) goto L_seg217_0EAE_000EDC; /* jne 0x0EDC */
    cpu->ax = (uint16_t)(0xC);               /* mov ax, 0xC */
    goto L_seg217_0EAE_000F39;               /* jmp 0x0F39 */
L_seg217_0EAE_000EFF:;
L_seg217_0EAE_000EFF:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov bx, word ss:[bp+-0x8] */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6A)); /* les ax, word ds:[bx+-0x7B6A] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx - 0x7B6A) + 2));
    cpu->cx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6E)); /* lds cx, word ds:[bx+-0x7B6E] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx - 0x7B6E) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_00A6(cpu);                        /* call 0x00A6 */
    cpu->cx = (uint16_t)(cpu->dx);           /* mov cx, dx */
    cpu->di = (uint16_t)(0x6);               /* mov di, 0x6 */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->si; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul si */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x186), (uint16_t)(cpu->ax)); /* mov word ds:[bx+di+0x186], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x188), (uint16_t)(cpu->cx)); /* mov word ds:[bx+di+0x188], cx */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* les si, word ss:[bp+-0x4] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->si + 0x18))); /* mov al, byte es:[si+0x18] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x184), (uint16_t)(cpu->ax)); /* mov word ds:[bx+di+0x184], ax */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x182), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x182)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word ds:[bx+0x182] */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg217_0EAE_000F39:;
L_seg217_0EAE_000F39:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_0F3E(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x10)); /* sub sp, 0x10 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0x4], si */
    cpu->ds = (uint16_t)(cpu->dx);           /* mov ds, dx */
    cpu->di = (uint16_t)(cpu->ax);           /* mov di, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x8], di */
    cpu->es = (uint16_t)(cpu->bx);           /* mov es, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x6], es */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->di + 0x484))); /* mov dx, word es:[di+0x484] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0xA], dx */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x19E))); /* mov di, word ds:[si+0x19E] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0xC], di */
    flags_cmp16(cpu, cpu->dx, 0x4000);       /* cmp dx, 0x4000 */
    if (cc_b(cpu)) goto L_seg217_0F3E_000F72; /* jb 0x0F72 */
    cpu->ax = (uint16_t)(0xB);               /* mov ax, 0xB */
    goto L_seg217_0F3E_000FE6;               /* jmp 0x0FE6 */
L_seg217_0F3E_000F72:;
L_seg217_0F3E_000F72:;
    cpu->ax = (uint16_t)(cpu->si);           /* mov ax, si */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0904(cpu);                        /* call 0x0904 */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    { uint16_t _v = cpu->dx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* shl dx, 0x1 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0xE], dx */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xC0)); /* sub bx, 0xC0 */
    if (cc_ne(cpu)) goto L_seg217_0F3E_000F8C; /* jne 0x0F8C */
    { uint16_t _r = cpu->cx ^ cpu->cx; flags_logic16(cpu, _r); cpu->cx = (uint16_t)(_r); } /* xor cx, cx */
    goto L_seg217_0F3E_001027;               /* jmp 0x1027 */
L_seg217_0F3E_000F8C:;
L_seg217_0F3E_000F8C:;
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFF0)); /* sub bx, 0xFFF0 */
    if (cc_e(cpu)) goto L_seg217_0F3E_000FF7; /* je 0x0FF7 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0xFFE0)); /* sub bx, 0xFFE0 */
    if (cc_ne(cpu)) goto L_seg217_0F3E_000FE4; /* jne 0x0FE4 */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* les bx, word ss:[bp+-0x8] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->di + 0x160))); /* mov ax, word es:[bx+di+0x160] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x10], ax */
    { uint16_t _r = cpu->dx ^ cpu->dx; flags_logic16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* xor dx, dx */
    goto L_seg217_0F3E_000FBB;               /* jmp 0x0FBB */
L_seg217_0F3E_000FA8:;
L_seg217_0F3E_000FA8:;
    cpu->si = (uint16_t)(cpu->dx);           /* mov si, dx */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x487))); /* mov al, byte es:[bx+si+0x487] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov di, word ss:[bp+-0x10] */
    flags_cmp16(cpu, cpu->ax, cpu->di);      /* cmp ax, di */
    if (cc_e(cpu)) goto L_seg217_0F3E_000FE8; /* je 0x0FE8 */
L_seg217_0F3E_000FBA:;
L_seg217_0F3E_000FBA:;
    { int _cf = cf(cpu); cpu->dx = (uint16_t)(flags_add16(cpu, cpu->dx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc dx */
L_seg217_0F3E_000FBB:;
L_seg217_0F3E_000FBB:;
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov cx, word ss:[bp+-0xA] */
    flags_cmp16(cpu, cpu->dx, cpu->cx);      /* cmp dx, cx */
    if (cc_b(cpu)) goto L_seg217_0F3E_000FA8; /* jb 0x0FA8 */
L_seg217_0F3E_000FC2:;
L_seg217_0F3E_000FC2:;
    flags_cmp16(cpu, cpu->dx, cpu->cx);      /* cmp dx, cx */
    if (cc_ne(cpu)) goto L_seg217_0F3E_000FE4; /* jne 0x0FE4 */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov bx, word ss:[bp+-0x8] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov si, word ss:[bp+-0xE] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x487), (uint8_t)(cpu->al)); /* mov byte es:[bx+si+0x487], al */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov di, word ss:[bp+-0x4] */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->di + 0x17))); /* mov al, byte ds:[di+0x17] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x486), (uint8_t)(cpu->al)); /* mov byte es:[bx+si+0x486], al */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x484), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x484)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word es:[bx+0x484] */
L_seg217_0F3E_000FE4:;
L_seg217_0F3E_000FE4:;
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
L_seg217_0F3E_000FE6:;
L_seg217_0F3E_000FE6:;
    goto L_seg217_0F3E_001067;               /* jmp 0x1067 */
L_seg217_0F3E_000FE8:;
L_seg217_0F3E_000FE8:;
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov di, word ss:[bp+-0x4] */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->di + 0x17))); /* mov al, byte ds:[di+0x17] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x486)), cpu->al); /* cmp byte es:[bx+si+0x486], al */
    if (cc_e(cpu)) goto L_seg217_0F3E_000FC2; /* je 0x0FC2 */
    goto L_seg217_0F3E_000FBA;               /* jmp 0x0FBA */
L_seg217_0F3E_000FF7:;
L_seg217_0F3E_000FF7:;
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x17))); /* mov al, byte ds:[si+0x17] */
    cpu->bx = (uint16_t)(cpu->ax);           /* mov bx, ax */
    cpu->bh = (uint8_t)(flags_sub8(cpu, cpu->bh, cpu->bh)); /* sub bh, bh */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, 0x72)); /* sub bx, 0x72 */
    if (cc_ne(cpu)) goto L_seg217_0F3E_000FE4; /* jne 0x0FE4 */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x18))); /* mov al, byte ds:[si+0x18] */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* lds bx, word ss:[bp+-0x8] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x150), (uint8_t)(cpu->al)); /* mov byte ds:[bx+di+0x150], al */
    goto L_seg217_0F3E_000FE4;               /* jmp 0x0FE4 */
L_seg217_0F3E_001010:;
L_seg217_0F3E_001010:;
    cpu->di = (uint16_t)(cpu->cx);           /* mov di, cx */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* les bx, word ss:[bp+-0x8] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov si, word ss:[bp+-0xC] */
    cpu->dl = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x150))); /* mov dl, byte es:[bx+si+0x150] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->di + 0x487)), cpu->dl); /* cmp byte es:[bx+di+0x487], dl */
    if (cc_e(cpu)) goto L_seg217_0F3E_001058; /* je 0x1058 */
L_seg217_0F3E_001026:;
L_seg217_0F3E_001026:;
    { int _cf = cf(cpu); cpu->cx = (uint16_t)(flags_add16(cpu, cpu->cx, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc cx */
L_seg217_0F3E_001027:;
L_seg217_0F3E_001027:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov ax, word ss:[bp+-0xA] */
    flags_cmp16(cpu, cpu->cx, cpu->ax);      /* cmp cx, ax */
    if (cc_b(cpu)) goto L_seg217_0F3E_001010; /* jb 0x1010 */
L_seg217_0F3E_00102E:;
L_seg217_0F3E_00102E:;
    flags_cmp16(cpu, cpu->cx, cpu->ax);      /* cmp cx, ax */
    if (cc_ne(cpu)) goto L_seg217_0F3E_000FE4; /* jne 0x0FE4 */
    cpu->bx = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8)); /* les bx, word ss:[bp+-0x8] */
    cpu->es = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x8) + 2));
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov si, word ss:[bp+-0xC] */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x150))); /* mov al, byte es:[bx+si+0x150] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov si, word ss:[bp+-0xE] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x487), (uint8_t)(cpu->al)); /* mov byte es:[bx+si+0x487], al */
    cpu->di = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov di, word ss:[bp+-0x4] */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->di + 0x17))); /* mov al, byte ds:[di+0x17] */
    mem_write8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->si + 0x486), (uint8_t)(cpu->al)); /* mov byte es:[bx+si+0x486], al */
    { int _cf = cf(cpu); mem_write16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x484), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->es, (uint16_t)(cpu->bx + 0x484)), 1))); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc word es:[bx+0x484] */
    goto L_seg217_0F3E_000FE4;               /* jmp 0x0FE4 */
L_seg217_0F3E_001058:;
L_seg217_0F3E_001058:;
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov si, word ss:[bp+-0x4] */
    cpu->dl = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->si + 0x17))); /* mov dl, byte ds:[si+0x17] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->es, (uint16_t)(cpu->bx + cpu->di + 0x486)), cpu->dl); /* cmp byte es:[bx+di+0x486], dl */
    if (cc_e(cpu)) goto L_seg217_0F3E_00102E; /* je 0x102E */
    goto L_seg217_0F3E_001026;               /* jmp 0x1026 */
L_seg217_0F3E_001067:;
L_seg217_0F3E_001067:;
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_106C(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x20)); /* sub sp, 0x20 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->di);                    /* push di */
    push16(cpu, cpu->si);                    /* push si */
    cpu->si = (uint16_t)(cpu->cx);           /* mov si, cx */
    cpu->es = (uint16_t)(cpu->dx);           /* mov es, dx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x4], ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->ds)); /* mov word ss:[bp+-0x2], ds */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->es, (uint16_t)(cpu->si + 0x19E))); /* mov ax, word es:[si+0x19E] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x6], ax */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->es, (uint16_t)(cpu->si + 0x17))); /* mov al, byte es:[si+0x17] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x8], ax */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0xA], si */
    /* jmp out of function to 0x0010CA */    /* jmp 0x10CA */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC))); /* mov si, word ss:[bp+-0xC] */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xD0)); /* les ax, word ds:[bx+si+0xD0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0xD0) + 2));
    cpu->cx = (uint16_t)(0xFFFF);            /* mov cx, 0xFFFF */
    cpu->dx = (uint16_t)(0xFFFF);            /* mov dx, 0xFFFF */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10))); /* mov ax, word ss:[bp+-0x10] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE))); /* mov bx, word ss:[bp+-0xE] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_063C(cpu);                        /* call 0x063C */
L_seg217_106C_0010BC:;
L_seg217_106C_0010BC:;
    cpu->si = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA))); /* mov si, word ss:[bp+-0xA] */
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xA), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0xA], si */
    flags_cmp16(cpu, cpu->si, 0x20);         /* cmp si, 0x20 */
    /* data byte: 0x0F */                    /* db 0xF */
    { uint16_t _r = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x1)) & 0xFF8B; flags_logic16(cpu, _r); mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp + 0x1), (uint16_t)(_r)); } /* and word ss:[bp+0x1], 0xFF8B */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->flags &= ~FLAG_DF;                  /* cld */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x10))); /* mov al, byte ds:[bx+si+0x10] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x6))); /* mov cx, word ss:[bp+-0x6] */
    flags_cmp16(cpu, cpu->ax, cpu->cx);      /* cmp ax, cx */
    if (cc_ne(cpu)) goto L_seg217_106C_0010BC; /* jne 0x10BC */
    cpu->al = (uint8_t)(mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x30))); /* mov al, byte ds:[bx+si+0x30] */
    cpu->ah = (uint8_t)(flags_sub8(cpu, cpu->ah, cpu->ah)); /* sub ah, ah */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x8))); /* mov cx, word ss:[bp+-0x8] */
    flags_cmp16(cpu, cpu->ax, cpu->cx);      /* cmp ax, cx */
    if (cc_ne(cpu)) goto L_seg217_106C_0010BC; /* jne 0x10BC */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x10), (uint8_t)(0xFF)); /* mov byte ds:[bx+si+0x10], 0xFF */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    { uint16_t _v = cpu->si; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->si = (uint16_t)(_r); } /* shl si, 0x1 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xC), (uint16_t)(cpu->si)); /* mov word ss:[bp+-0xC], si */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x8))); /* mov ax, word ds:[bx+0x8] */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0xA))); /* mov cx, word ds:[bx+0xA] */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x50)))); /* sub ax, word ds:[bx+si+0x50] */
    cpu->cx = (uint16_t)(flags_sub16(cpu, cpu->cx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x52)) + cf(cpu))); /* sbb cx, word ds:[bx+si+0x52] */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x10), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x10], ax */
    cpu->bx = (uint16_t)(cpu->cx);           /* mov bx, cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0xE), (uint16_t)(cpu->bx)); /* mov word ss:[bp+-0xE], bx */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0620(cpu);                        /* call 0x0620 */
    cpu->dx = (uint16_t)(0x0);               /* mov dx, 0x0 */
    cpu->ax = (uint16_t)(flags_add16(cpu, cpu->ax, 0xFFFF)); /* add ax, 0xFFFF */
    cpu->dx = (uint16_t)(flags_add16(cpu, cpu->dx, 0xFFFF + cf(cpu))); /* adc dx, 0xFFFF */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x14], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x12], dx */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    { uint16_t _r = cpu->bx | cpu->ax; flags_logic16(cpu, _r); cpu->bx = (uint16_t)(_r); } /* or bx, ax */
    /* data byte: 0x0F */                    /* db 0xF */
    flags_logic8(cpu, mem_read8(cpu, cpu->ss, (uint16_t)(cpu->bp + cpu->di - 0x1)) & cpu->bh); /* test byte ss:[bp+di+-0x1], bh */
    cpu->cx = (uint16_t)(cpu->ax);           /* mov cx, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18), (uint16_t)(cpu->cx)); /* mov word ss:[bp+-0x18], cx */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x16], dx */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xD0)); /* les ax, word ds:[bx+si+0xD0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0xD0) + 2));
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C), (uint16_t)(cpu->ax)); /* mov word ss:[bp+-0x1C], ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A), (uint16_t)(cpu->dx)); /* mov word ss:[bp+-0x1A], dx */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->di = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xD0)); /* les di, word ds:[bx+si+0xD0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0xD0) + 2));
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x1E], es */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20), (uint16_t)(cpu->di)); /* mov word ss:[bp+-0x20], di */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6A)); /* les ax, word ds:[bx+-0x7B6A] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx - 0x7B6A) + 2));
    cpu->cx = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0xD0)); /* lds cx, word ds:[bx+si+0xD0] */
    cpu->ds = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->si + 0xD0) + 2));
    cpu->dx = (uint16_t)(cpu->ds);           /* mov dx, ds */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_00A6(cpu);                        /* call 0x00A6 */
    push16(cpu, cpu->ax);                    /* push ax */
    cpu->cx = (uint16_t)(cpu->di);           /* mov cx, di */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E))); /* mov dx, word ss:[bp+-0x1E] */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1C))); /* mov ax, word ss:[bp+-0x1C] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1A))); /* mov bx, word ss:[bp+-0x1A] */
    /* unresolved far call call 0000:1757 */ /* call 0000:1757 */
    cpu->si = mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4)); /* lds si, word ss:[bp+-0x4] */
    cpu->ds = mem_read16(cpu, cpu->ss, (uint16_t)((uint16_t)(cpu->bp - 0x4) + 2));
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B6A)); /* les ax, word ds:[si+-0x7B6A] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->si - 0x7B6A) + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18))); /* mov cx, word ss:[bp+-0x18] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16))); /* mov dx, word ss:[bp+-0x16] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B6A), (uint16_t)(cpu->ax)); /* mov word ds:[si+-0x7B6A], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B68), (uint16_t)(cpu->dx)); /* mov word ds:[si+-0x7B68], dx */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov ax, word ss:[bp+-0x14] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B7A), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B7A)), cpu->ax))); /* add word ds:[si+-0x7B7A], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov ax, word ss:[bp+-0x12] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B78), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si - 0x7B78)), cpu->ax + cf(cpu)))); /* adc word ds:[si+-0x7B78], ax */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
L_seg217_106C_001193:;
L_seg217_106C_001193:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    flags_cmp8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->si + 0x10)), 0xFF); /* cmp byte ds:[bx+si+0x10], 0xFF */
    if (cc_e(cpu)) goto L_seg217_106C_0011DA; /* je 0x11DA */
    cpu->di = (uint16_t)(cpu->si);           /* mov di, si */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    { uint16_t _v = cpu->di; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->di = (uint16_t)(_r); } /* shl di, 0x1 */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0xD0)); /* les ax, word ds:[bx+di+0xD0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0xD0) + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20))); /* mov cx, word ss:[bp+-0x20] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E))); /* mov dx, word ss:[bp+-0x1E] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_00A6(cpu);                        /* call 0x00A6 */
    flags_logic16(cpu, cpu->dx & cpu->dx);   /* test dx, dx */
    if (cc_l(cpu)) goto L_seg217_106C_0011DA; /* jl 0x11DA */
    if (cc_g(cpu)) goto L_seg217_106C_0011BC; /* jg 0x11BC */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_b(cpu)) goto L_seg217_106C_0011DA; /* jb 0x11DA */
L_seg217_106C_0011BC:;
L_seg217_106C_0011BC:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0xD0)); /* les ax, word ds:[bx+di+0xD0] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx + cpu->di + 0xD0) + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x18))); /* mov cx, word ss:[bp+-0x18] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x16))); /* mov dx, word ss:[bp+-0x16] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0xD0), (uint16_t)(cpu->ax)); /* mov word ds:[bx+di+0xD0], ax */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0xD2), (uint16_t)(cpu->dx)); /* mov word ds:[bx+di+0xD2], dx */
L_seg217_106C_0011DA:;
L_seg217_106C_0011DA:;
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    flags_cmp16(cpu, cpu->si, 0x20);         /* cmp si, 0x20 */
    if (cc_b(cpu)) goto L_seg217_106C_001193; /* jb 0x1193 */
    { uint16_t _r = cpu->si ^ cpu->si; flags_logic16(cpu, _r); cpu->si = (uint16_t)(_r); } /* xor si, si */
L_seg217_106C_0011E2:;
L_seg217_106C_0011E2:;
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + 0x182)), cpu->si); /* cmp word ds:[bx+0x182], si */
    /* data byte: 0x0F */                    /* db 0xF */
    { uint16_t _t = mem_read8(cpu, cpu->ds, (uint16_t)(cpu->di - 0x4002)); mem_write8(cpu, cpu->ds, (uint16_t)(cpu->di - 0x4002), (uint8_t)(cpu->ch)); cpu->ch = (uint8_t)(_t); } /* xchg byte ds:[di+-0x4002], ch */
    push16(cpu, cpu->es);                    /* push es */
    mem_write8(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x1909), (uint8_t)(flags_add8(cpu, mem_read8(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x1909)), cpu->dl))); /* add byte ds:[bx+-0x1909], dl */
    { uint16_t _t = cpu->ax; cpu->ax = (uint16_t)(cpu->di); cpu->di = (uint16_t)(_t); } /* xchg ax, di */
    cpu->ax = mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx - 0x7B6E)); /* les ax, word ds:[bx+-0x7B6E] */
    cpu->es = mem_read16(cpu, cpu->ds, (uint16_t)((uint16_t)(cpu->bx - 0x7B6E) + 2));
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x186))); /* mov cx, word ds:[bx+di+0x186] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x188))); /* mov dx, word ds:[bx+di+0x188] */
    cpu->bx = (uint16_t)(cpu->es);           /* mov bx, es */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_0000(cpu);                        /* call 0x0000 */
    cpu->bx = (uint16_t)(cpu->dx);           /* mov bx, dx */
    cpu->cx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x20))); /* mov cx, word ss:[bp+-0x20] */
    cpu->dx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x1E))); /* mov dx, word ss:[bp+-0x1E] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_00A6(cpu);                        /* call 0x00A6 */
    flags_logic16(cpu, cpu->dx & cpu->dx);   /* test dx, dx */
    if (cc_l(cpu)) goto L_seg217_106C_00122D; /* jl 0x122D */
    if (cc_g(cpu)) goto L_seg217_106C_00121C; /* jg 0x121C */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_b(cpu)) goto L_seg217_106C_00122D; /* jb 0x122D */
L_seg217_106C_00121C:;
L_seg217_106C_00121C:;
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x14))); /* mov ax, word ss:[bp+-0x14] */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x186), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x186)), cpu->ax))); /* add word ds:[bx+di+0x186], ax */
    cpu->ax = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x12))); /* mov ax, word ss:[bp+-0x12] */
    mem_write16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x188), (uint16_t)(flags_add16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->bx + cpu->di + 0x188)), cpu->ax + cf(cpu)))); /* adc word ds:[bx+di+0x188], ax */
L_seg217_106C_00122D:;
L_seg217_106C_00122D:;
    { int _cf = cf(cpu); cpu->si = (uint16_t)(flags_add16(cpu, cpu->si, 1)); if (_cf) cpu->flags |= FLAG_CF; else cpu->flags &= ~FLAG_CF; } /* inc si */
    goto L_seg217_106C_0011E2;               /* jmp 0x11E2 */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->di = (uint16_t)(pop16(cpu));        /* pop di */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

void seg217_12DC(CPU *cpu)
{
    push16(cpu, cpu->bp);                    /* push bp */
    cpu->bp = (uint16_t)(cpu->sp);           /* mov bp, sp */
    cpu->sp = (uint16_t)(flags_sub16(cpu, cpu->sp, 0x4)); /* sub sp, 0x4 */
    push16(cpu, cpu->ds);                    /* push ds */
    push16(cpu, cpu->si);                    /* push si */
    push16(cpu, cpu->dx);                    /* push dx */
    push16(cpu, cpu->cx);                    /* push cx */
    cpu->si = (uint16_t)(cpu->ax);           /* mov si, ax */
    cpu->ds = (uint16_t)(cpu->bx);           /* mov ds, bx */
    cpu->bx = (uint16_t)(0x13F5);            /* mov bx, 0x13F5 */
    cpu->ax = (uint16_t)(SEG_22);            /* mov ax, 0xFFFF  /* selector for seg22 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x2], es */
    cpu->ax = (uint16_t)(0x1A);              /* mov ax, 0x1A */
    cpu->cx = (uint16_t)(cpu->bx);           /* mov cx, bx */
    mem_write16(cpu, cpu->es, 0x8, (uint16_t)(cpu->ax)); /* mov word es:[0x8], ax */
    mem_write16(cpu, cpu->es, 0xA, (uint16_t)(cpu->cx)); /* mov word es:[0xA], cx */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x484)); /* lea ax, word ds:[si+0x484] */
    cpu->cx = (uint16_t)(cpu->ds);           /* mov cx, ds */
    mem_write16(cpu, cpu->es, 0xC, (uint16_t)(cpu->ax)); /* mov word es:[0xC], ax */
    mem_write16(cpu, cpu->es, 0xE, (uint16_t)(cpu->cx)); /* mov word es:[0xE], cx */
    cpu->cx = (uint16_t)(0x0);               /* mov cx, 0x0 */
    cpu->dx = (uint16_t)(0x4000);            /* mov dx, 0x4000 */
    cpu->dx = (uint16_t)(flags_sub16(cpu, cpu->dx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x484)))); /* sub dx, word ds:[si+0x484] */
    { uint16_t _v = cpu->dx; uint8_t _c = 0x1; uint16_t _r = _v << _c; cpu->flags = (cpu->flags & ~FLAG_CF) | ((_v >> (16 - _c)) & 1 ? FLAG_CF : 0); flags_shift16(cpu, _r); cpu->dx = (uint16_t)(_r); } /* shl dx, 0x1 */
    cpu->ax = (uint16_t)(0x8002);            /* mov ax, 0x8002 */
    cpu->ax = (uint16_t)(flags_sub16(cpu, cpu->ax, cpu->dx)); /* sub ax, dx */
    mem_write16(cpu, cpu->es, 0, (uint16_t)(cpu->ax)); /* mov word es:[0x0], ax */
    mem_write16(cpu, cpu->es, 0x2, (uint16_t)(cpu->cx)); /* mov word es:[0x2], cx */
    cpu->ax = (uint16_t)(SEG_20);            /* mov ax, 0xFFFF  /* selector for seg20 */ */
    cpu->es = (uint16_t)(cpu->ax);           /* mov es, ax */
    mem_write16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4), (uint16_t)(cpu->es)); /* mov word ss:[bp+-0x4], es */
    cpu->ax = (uint16_t)(0x1F);              /* mov ax, 0x1F */
    mem_write16(cpu, cpu->es, 0x8, (uint16_t)(cpu->ax)); /* mov word es:[0x8], ax */
    mem_write16(cpu, cpu->es, 0xA, (uint16_t)(cpu->bx)); /* mov word es:[0xA], bx */
    cpu->ax = (uint16_t)((uint16_t)(cpu->si + 0x182)); /* lea ax, word ds:[si+0x182] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    mem_write16(cpu, cpu->es, 0xC, (uint16_t)(cpu->ax)); /* mov word es:[0xC], ax */
    mem_write16(cpu, cpu->es, 0xE, (uint16_t)(cpu->bx)); /* mov word es:[0xE], bx */
    cpu->cx = (uint16_t)(0x0);               /* mov cx, 0x0 */
    cpu->bx = (uint16_t)(0x80);              /* mov bx, 0x80 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x182)))); /* sub bx, word ds:[si+0x182] */
    cpu->ax = (uint16_t)(0x6);               /* mov ax, 0x6 */
    { uint32_t _r = (uint32_t)cpu->ax * cpu->bx; cpu->ax = (uint16_t)_r; cpu->dx = (uint16_t)(_r >> 16); cpu->flags = (cpu->flags & ~(FLAG_CF|FLAG_OF)) | (cpu->dx ? FLAG_CF|FLAG_OF : 0); } /* mul bx */
    cpu->bx = (uint16_t)(0x302);             /* mov bx, 0x302 */
    cpu->bx = (uint16_t)(flags_sub16(cpu, cpu->bx, cpu->ax)); /* sub bx, ax */
    cpu->ax = (uint16_t)(cpu->bx);           /* mov ax, bx */
    mem_write16(cpu, cpu->es, 0, (uint16_t)(cpu->ax)); /* mov word es:[0x0], ax */
    mem_write16(cpu, cpu->es, 0x2, (uint16_t)(cpu->cx)); /* mov word es:[0x2], cx */
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x484)), 0x0); /* cmp word ds:[si+0x484], 0x0 */
    if (cc_ne(cpu)) goto L_seg217_12DC_00138F; /* jne 0x138F */
L_seg217_12DC_001375:;
L_seg217_12DC_001375:;
    flags_cmp16(cpu, mem_read16(cpu, cpu->ds, (uint16_t)(cpu->si + 0x182)), 0x0); /* cmp word ds:[si+0x182], 0x0 */
    if (cc_e(cpu)) goto L_seg217_12DC_0013A2; /* je 0x13A2 */
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x4))); /* mov bx, word ss:[bp+-0x4] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_02A8(cpu);                        /* call 0x02A8 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg217_12DC_0013A2; /* jne 0x13A2 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    goto L_seg217_12DC_0013B7;               /* jmp 0x13B7 */
L_seg217_12DC_00138F:;
L_seg217_12DC_00138F:;
    cpu->ax = (uint16_t)(0x0);               /* mov ax, 0x0 */
    cpu->bx = (uint16_t)(mem_read16(cpu, cpu->ss, (uint16_t)(cpu->bp - 0x2))); /* mov bx, word ss:[bp+-0x2] */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_02A8(cpu);                        /* call 0x02A8 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_ne(cpu)) goto L_seg217_12DC_001375; /* jne 0x1375 */
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
    goto L_seg217_12DC_0013B7;               /* jmp 0x13B7 */
L_seg217_12DC_0013A2:;
L_seg217_12DC_0013A2:;
    cpu->ax = (uint16_t)((uint16_t)(cpu->si - 0x7B7A)); /* lea ax, word ds:[si+-0x7B7A] */
    cpu->bx = (uint16_t)(cpu->ds);           /* mov bx, ds */
    push16(cpu, cpu->cs);                    /* push cs */
    push16(cpu, 0);                          /* near call return addr */
    seg217_02A8(cpu);                        /* call 0x02A8 */
    flags_logic16(cpu, cpu->ax & cpu->ax);   /* test ax, ax */
    if (cc_e(cpu)) goto L_seg217_12DC_0013B4; /* je 0x13B4 */
    { uint16_t _r = cpu->ax ^ cpu->ax; flags_logic16(cpu, _r); cpu->ax = (uint16_t)(_r); } /* xor ax, ax */
    goto L_seg217_12DC_0013B7;               /* jmp 0x13B7 */
L_seg217_12DC_0013B4:;
L_seg217_12DC_0013B4:;
    cpu->ax = (uint16_t)(0x1);               /* mov ax, 0x1 */
L_seg217_12DC_0013B7:;
L_seg217_12DC_0013B7:;
    cpu->cx = (uint16_t)(pop16(cpu));        /* pop cx */
    cpu->dx = (uint16_t)(pop16(cpu));        /* pop dx */
    cpu->si = (uint16_t)(pop16(cpu));        /* pop si */
    cpu->ds = (uint16_t)(pop16(cpu));        /* pop ds */
    cpu->sp = cpu->bp; cpu->bp = pop16(cpu); /* leave */
    cpu->sp += 4; return;                    /* retf */
}

